Repository devitocodes/devito, pull requests merged in 2018-05, with the labels that each got.

#560 ir: ScheduleTree level
  devito/dle/backends/advanced.py
  devito/dse/backends/advanced.py
  devito/ir/clusters/cluster.py
  devito/ir/equations/equation.py
  devito/ir/iet/nodes.py
  devito/ir/iet/scheduler.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/ir/stree/__init__.py
  devito/ir/stree/algorithms.py
  devito/ir/stree/tree.py
  devito/ir/support/space.py
  devito/operator.py
  devito/profiling.py
  devito/symbolics/inspection.py
  devito/yask/operator.py
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  requirements.txt
  tests/test_dse.py
  tests/test_operator.py
Labels: review

#557 Update YASK interface to use newer grid APIs for left/right halos/pads.
  devito/yask/data.py
  devito/yask/function.py
  devito/yask/wrappers.py
Labels: in progress

#570 run codecove with yask
  .travis.yml
Labels: in progress

#572 bugfix: clear_cache() was missing from the RTM tutorial and misplaced…
  examples/seismic/tutorials/02_rtm.ipynb
  examples/seismic/tutorials/03_fwi.ipynb
Labels: bug, review

#562 fix dle handling of subdimensions
  devito/core/autotuning.py
  devito/core/operator.py
  devito/dimension.py
  devito/dle/backends/advanced.py
  devito/dle/backends/basic.py
  devito/dle/blocking_utils.py
  devito/ir/iet/nodes.py
  devito/ir/support/space.py
  devito/operator.py
  tests/test_dimension.py
Labels: in progress

#553 Spatial conditionals
  devito/dimension.py
  devito/function.py
  devito/ir/clusters/algorithms.py
  devito/ir/iet/scheduler.py
  tests/test_derivatives.py
  tests/test_dimension.py
  tests/test_operator.py
Labels: enhancement, next

#583 Examples cleanup
  .travis.yml
  devito/cgen_utils.py
  devito/function.py
  devito/grid.py
  devito/ir/iet/visitors.py
  examples/checkpointing/checkpoint.py
  examples/checkpointing/checkpointing_example.py
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/acoustic/gradient_example.py
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/model.py
  examples/seismic/source.py
  examples/seismic/tti/operators.py
  examples/seismic/tti/tti_example.py
  examples/seismic/tti/wavesolver.py
  tests/conftest.py
  tests/test_adjoint.py
  tests/test_adjointA.py
  tests/test_adjointJ.py
  tests/test_checkpointing.py
  tests/test_derivatives.py
  tests/test_finite_difference.py
  tests/test_gradient.py
  tests/test_interpolation.py
  tests/test_resample.py
  tests/test_yask.py
Labels: better code, enhancement

#588 Fix Dimension caching
  devito/dimension.py
  tests/test_dimension.py
  tests/test_symbol_caching.py
Labels: review
