Repository devitocodes/devito, pull requests merged in 2018-12, with the labels that each got.

#714 Set up CI with Azure Pipelines
  Dockerfile.jenkins
  Dockerfile.pipelines
  Jenkinsfile
  azure-pipelines.py
  azure-pipelines.yml
Labels: testing

#735 Tutorials improvements
  examples/cfd/03_diffusion.ipynb
  examples/cfd/03_diffusion_nonuniform.ipynb
  examples/cfd/04_burgers.ipynb
Labels: good for newcomers, in progress

#740 Restrict testing on pipelines
  azure-pipelines.yml
Labels: enhancement, testing
