Repository devitocodes/devito, pull requests merged in 2019-08, with the labels that each got.

#887 bench: autotuning args and README updates
  .travis.yml
  azure-pipelines.py
  benchmarks/user/README.md
  benchmarks/user/benchmark.py
  devito/__init__.py
  devito/core/operator.py
  devito/yask/wrappers.py
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/elastic/elastic_example.py
  examples/seismic/tti/tti_example.py
Labels: documentation, good for newcomers

#824 Data slice fix
  devito/data/__init__.py
  devito/data/data.py
  devito/data/decomposition.py
  devito/data/utils.py
  devito/mpi/distributed.py
  devito/types/dense.py
  tests/test_data.py
  tests/test_docstrings.py
  tests/test_interpolation.py
Labels: RFC

#911 Model cleanup
  .travis.yml
  azure-pipelines.py
  devito/compiler.py
  examples/seismic/model.py
  examples/seismic/tti/operators.py
  tests/test_dse.py
  tests/test_mpi.py
Labels: RFC, better code, enhancement
