Repository devitocodes/devito, pull requests merged in 2019-05, with the labels that each got.

#794 fast math with gcc
  devito/compiler.py
  tests/test_dle.py
  tests/test_operator.py
Labels: RFC, enhancement

#826 Numpy-doc examples/* and tests/test_derivatives.py
  examples/cfd/example_diffusion.py
  examples/cfd/tools.py
  examples/checkpointing/checkpoint.py
  examples/seismic/acoustic/operators.py
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/elastic/operators.py
  examples/seismic/elastic/wavesolver.py
  examples/seismic/model.py
  examples/seismic/plotting.py
  examples/seismic/tti/operators.py
  examples/seismic/tti/wavesolver.py
  tests/test_derivatives.py
Labels: RFC, documentation, good for newcomers, help wanted, in progress

#833 plot_field(...) enhancements
  examples/cfd/tools.py
Labels: better code
