Repository devitocodes/devito, pull requests merged in 2019-11, with the labels that each got.

#978 Devito smooth
  devito/builtins.py
  examples/seismic/model.py
  examples/seismic/utils.py
  tests/test_builtins.py
Labels: good for newcomers, in progress

#873 Tensorial analysis
  devito/__init__.py
  devito/equation.py
  devito/finite_differences/__init__.py
  devito/finite_differences/coefficients.py
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/finite_differences/operators.py
  devito/finite_differences/tools.py
  devito/ir/equations/algorithms.py
  devito/ir/support/basic.py
  devito/operator.py
  devito/profiling.py
  devito/types/__init__.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/sparse.py
  devito/types/tensor.py
  devito/yask/types.py
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  examples/cfd/02_convection_nonlinear.ipynb
  examples/cfd/04_burgers.ipynb
  examples/cfd/05_laplace.ipynb
  examples/seismic/acoustic/operators.py
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/elastic/elastic_example.py
  examples/seismic/elastic/operators.py
  examples/seismic/elastic/wavesolver.py
  examples/seismic/model.py
  examples/seismic/plotting.py
  examples/seismic/tti/operators.py
  examples/seismic/tutorials/01_modelling.ipynb
  examples/seismic/tutorials/02_rtm.ipynb
  examples/seismic/tutorials/03_fwi.ipynb
  examples/seismic/tutorials/05_staggered_acoustic.ipynb
  examples/seismic/tutorials/06_bis_elastic_varying_parameters.ipynb
  examples/seismic/tutorials/06_elastic.ipynb
  examples/seismic/tutorials/07_DRP_schemes.ipynb
  examples/seismic/tutorials/09_viscoelastic.ipynb
  examples/seismic/viscoelastic/operators.py
  examples/seismic/viscoelastic/viscoelastic_example.py
  examples/seismic/viscoelastic/wavesolver.py
  tests/test_caching.py
  tests/test_derivatives.py
  tests/test_dimension.py
  tests/test_mpi.py
  tests/test_operator.py
  tests/test_staggered_utils.py
  tests/test_symbolic_coefficients.py
  tests/test_tensors.py
  tests/test_yask.py
Labels: RFC, enhancement

#1012 Fixups for OpenMP-based GPU offloading
  devito/dle/parallelizer.py
  devito/dle/rewriters.py
  devito/yask/dle.py
  tests/test_dle.py
Labels: enhancement

#1003 Rework cluster fissioning
  devito/ir/clusters/algorithms.py
  devito/ir/support/basic.py
  devito/tools/memoization.py
  devito/types/grid.py
  devito/yask/types.py
  tests/test_operator.py
Labels: better code, documentation, enhancement
