Repository devitocodes/devito, pull requests merged in 2020-12, with the labels that each got.

#1438 Improve bitwise reproducibility
  devito/__init__.py
  devito/compiler.py
  devito/ir/support/utils.py
  devito/parameters.py
  examples/seismic/acoustic/accuracy.ipynb
  tests/test_gradient.py
  tests/test_roundoff.py
Labels: bug-C, compiler

#1523 operator: Patch grid-carried argument overrides
  devito/operator/operator.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/sparse.py
  tests/test_operator.py
Labels: bug-py-minor, compiler, minor-patch

#1519 Add test that compares gradient equivalence
  tests/test_gradient.py
Labels: DevOps, testing

#1515 Fix ARM issues
  devito/archinfo.py
  devito/core/__init__.py
  devito/core/arm.py
  devito/core/cpu.py
  devito/core/intel.py
  devito/core/power.py
Labels: compiler, enhancement

#1534 Fix loop collapsing
  devito/archinfo.py
  devito/ir/clusters/analysis.py
  devito/ir/equations/equation.py
  devito/ir/support/basic.py
  tests/test_dle.py
Labels: bug-C, compiler

#1535 Patch aliases' min-storage option
  devito/passes/clusters/aliases.py
  tests/test_dse.py
Labels: bug-py-minor, compiler, minor-patch
