Repository devitocodes/devito, pull requests merged in 2020-02, with the labels that each got.

#1108 Resurrect DSL introduction tutorial
  examples/userapi/00_dsl.ipynb
  examples/userapi/01_apply.ipynb
  examples/userapi/02_subdomains.ipynb
  examples/userapi/figures/grid.png
  examples/userapi/figures/stencil_backward.png
  examples/userapi/figures/stencil_convection.png
  examples/userapi/figures/stencil_forward.png
Labels: RFC, WIP, documentation

#1115 Misc clean up and consolidation
  devito/ir/clusters/analysis.py
  devito/ir/clusters/cluster.py
  devito/ir/clusters/queue.py
  devito/ir/iet/analysis.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/iet/scheduler.py
  devito/ir/iet/visitors.py
  devito/ir/stree/algorithms.py
  devito/ir/support/basic.py
  devito/ir/support/properties.py
  devito/ir/support/space.py
  devito/mpi/halo_scheme.py
  devito/operator/operator.py
  devito/passes/clusters/cse.py
  devito/passes/iet/misc.py
  devito/passes/iet/mpi.py
  devito/symbolics/manipulation.py
  devito/tools/algorithms.py
  examples/compiler/03_iet-A.ipynb
  tests/test_ir.py
  tests/test_mpi.py
Labels: better code, bug-py, enhancement

#1123 Resurrect openmp device offloading
  devito/core/gpu.py
  devito/passes/iet/definitions.py
  tests/test_dle.py
  tests/test_operator.py
Labels: azure, enhancement

#1125 bench: Add run-jit-backdoor mode
  benchmarks/user/README.md
  benchmarks/user/benchmark.py
Labels: azure, enhancement

#1129 Revamp README.md
  README.md
  examples/README.md
Labels: RFC, WIP, documentation, enhancement, help wanted

#1131 Add GPU CI
  .github/azure/deployVM.ps1
  .github/workflows/pytest-gpu.yml
  devito/archinfo.py
  tests/test_dle.py
  tests/test_gpu.py
Labels: DevOps, RFC

#1136 Patch benchmark
  benchmarks/user/benchmark.py
Labels: minor-patch

#1124 Extend GPU support via openmp offloading
  .github/workflows/pytest-gpu.yml
  devito/builtins.py
  devito/core/__init__.py
  devito/core/gpu.py
  devito/core/gpu_openmp.py
  devito/ir/clusters/analysis.py
  devito/ir/iet/nodes.py
  devito/ir/stree/algorithms.py
  devito/ir/support/basic.py
  devito/passes/iet/definitions.py
  devito/passes/iet/openmp.py
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_builtins.py
  tests/test_dimension.py
  tests/test_gpu.py
  tests/test_gpu_openmp.py
  tests/test_ir.py
  tests/test_operator.py
Labels: azure, enhancement

#1148 Fix memory leaks on GPU
  devito/core/gpu_openmp.py
  tests/test_gpu_openmp.py
Labels: bug-performance-gpu

#1142 [WIP-RFC--OGHPC] Initial PGI-support
  benchmarks/user/README.md
  devito/compiler.py
Labels: enhancement

#1144 Flexible Operators (now accepting 'compiler' and 'platform')
  .github/workflows/tutorials.yml
  devito/builtins.py
  devito/compiler.py
  devito/operator/operator.py
  devito/operator/registry.py
  examples/README.md
  examples/gpu/01_diffusion_with_openmp_offloading.ipynb
  examples/gpu/__init__.py
  tests/test_operator.py
Labels: enhancement
