Repository devitocodes/devito, pull requests merged in 2020-01, with the labels that each got.

#1068 Pytest actions
  .coveragerc
  .github/workflows/flake8.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-ops.yml
  .github/workflows/pytest-yask.yml
  .travis.yml
  Dockerfile.pipelines
  README.md
  azure-pipelines.py
  azure-pipelines.yml
  setup.cfg
  tests/test_checkpointing.py
  tests/test_installation.py
Labels: DevOps, testing

#1072 GitHub Action to publish to pypi
  .github/workflows/pythonpublish.yml
Labels: DevOps

#1061 Initial documentation action
  .github/workflows/documentation.yml
Labels: DevOps, documentation

#1075 doc update
  docs/source/equation.rst
  docs/source/operator.rst
  docs/source/symbolic.rst
  docs/source/tensorfunction.rst
  docs/source/tensortimefunction.rst
  docs/source/vectorfunction.rst
  docs/source/vectortimefunction.rst
Labels: documentation, minor-patch

#1042 Test cleanup
  devito/builtins.py
  examples/seismic/acoustic/operators.py
  examples/seismic/model.py
  examples/seismic/tutorials/03_fwi.ipynb
  examples/seismic/tutorials/04_dask.ipynb
  tests/conftest.py
  tests/test_adjoint.py
  tests/test_checkpointing.py
  tests/test_data.py
  tests/test_dependency_bugs.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_environment.py
  tests/test_interpolation.py
  tests/test_ir.py
  tests/test_operator.py
  tests/test_visitors.py
Labels: better code, minor-patch, testing

#1070 Created pytest core for mac
  .github/workflows/pytest-core-nompi.yml
Labels: DevOps, testing

#1049 Patch yreplace()
  devito/symbolics/manipulation.py
  tests/test_dse.py
Labels: bug, minor-patch

#1044 Fix openmp collapsing
  devito/ir/iet/visitors.py
  devito/targets/common/openmp.py
  tests/test_dle.py
Labels: bug-performance-C, minor-patch

#1080 Fix issue 1060
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-ops.yml
  .github/workflows/pytest-yask.yml
  devito/targets/common/blocking.py
  tests/test_dle.py
Labels: bug-py, minor-patch

#1084 Fix issue 1081
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/cluster.py
  devito/ir/support/basic.py
  devito/types/dimension.py
  tests/test_dimension.py
Labels: bug-performance-py, bug-py, minor-patch

#1079 Tutos examples
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-yask.yml
  .github/workflows/tutorials.yml
  docker/Dockerfile
  tests/test_environment.py
Labels: DevOps, testing

#1022 Topo fix
  devito/passes/clusters/cse.py
  tests/test_dse.py
Labels: bug-py, testing

#1085 Test DevitoBench
  docker/Dockerfile
  requirements.txt
  setup.py
  tests/test_benchmark.py
Labels: testing
