Repository devitocodes/devito, pull requests merged in 2020-06, with the labels that each got.

#1322 Bench update
  benchmarks/user/benchmark.py
  examples/seismic/model.py
  examples/seismic/skew_self_adjoint/wavesolver.py
  examples/seismic/utils.py
  tests/test_benchmark.py
Labels: RFC

#1324 Bench update
  benchmarks/user/benchmark.py
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/inversion/fwi.py
  examples/seismic/skew_self_adjoint/example_iso.py
  examples/seismic/skew_self_adjoint/ssa_03_iso_correctness.ipynb
  examples/seismic/skew_self_adjoint/test_wavesolver_iso.py
  examples/seismic/skew_self_adjoint/wavesolver.py
  tests/test_adjoint.py
  tests/test_benchmark.py
  tests/test_gradient.py
Labels: RFC, minor-patch

#1327 fix ssa notebook
  examples/seismic/skew_self_adjoint/ssa_01_iso_implementation1.ipynb
  examples/seismic/skew_self_adjoint/ssa_02_iso_implementation2.ipynb
  examples/seismic/skew_self_adjoint/ssa_03_iso_correctness.ipynb
  examples/seismic/tutorials/01_modelling.ipynb
  examples/seismic/tutorials/10_nmo_correction.ipynb
Labels: bug-py-minor, minor-patch

#1333 examples: Fixup default space order
  examples/seismic/utils.py
Labels: bug-py-minor

#1318 Improve CIRE
  devito/core/cpu.py
  devito/core/gpu_openmp.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/cse.py
  devito/symbolics/manipulation.py
  devito/symbolics/queries.py
  devito/symbolics/search.py
  examples/gpu/01_diffusion_with_openmp_offloading.ipynb
  tests/test_dse.py
Labels: RFC, better code, bug-performance-py, enhancement

#1328 enforce user provided x0
  devito/finite_differences/derivative.py
  devito/types/basic.py
  tests/test_derivatives.py
Labels: RFC, bug-py-minor, minor-patch

#1338 CI: add autolog of PRs
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
Labels: DevOps

#1339 elastic-fix
  examples/seismic/elastic/elastic_example.py
  examples/seismic/model.py
  examples/seismic/tutorials/06_elastic_varying_parameters.ipynb
  examples/seismic/viscoelastic/viscoelastic_example.py
Labels: bug-py-minor, examples, minor-patch

#1341 Fix numeric indices
  devito/types/basic.py
  tests/test_derivatives.py
  tests/test_symbolics.py
Labels: bug-py-minor, minor-patch

#1343 Indexify with non-symbolic numeric indices
  devito/types/basic.py
  tests/test_symbolics.py
Labels: bug-py-minor, minor-patch

#1345 Replace subdimension in expressions
  devito/ir/equations/algorithms.py
  examples/userapi/04_boundary_conditions.ipynb
  tests/test_subdomains.py
Labels: Compiler, bug-py, minor-patch

#1342 Improve solve speed for complicated equations
  devito/finite_differences/derivative.py
  devito/types/equation.py
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  examples/cfd/02_convection_nonlinear.ipynb
  examples/cfd/03_diffusion.ipynb
  examples/cfd/03_diffusion_nonuniform.ipynb
  examples/cfd/04_burgers.ipynb
  examples/cfd/05_laplace.ipynb
  examples/cfd/06_poisson.ipynb
  examples/gpu/01_diffusion_with_openmp_offloading.ipynb
  examples/seismic/acoustic/operators.py
  examples/seismic/tti/operators.py
  examples/userapi/01_dsl.ipynb
  tests/test_dse.py
  tests/test_symbolics.py
Labels: API, RFC, enhancement, examples

#1316 Avoid dererencing dangling pointers on GC'd objects
  devito/types/dense.py
Labels: bug-py-minor, compiler

#1352 Improve detection of redundant halo exchanges
  devito/passes/iet/mpi.py
  tests/test_mpi.py
Labels: MPI, bug-performance-C, compiler, minor-patch

#1351 Add binder directory with requirements.txt including matplotlib
  README.md
  binder/README.md
  binder/requirements.txt
  examples/seismic/skew_self_adjoint/ssa_01_iso_implementation1.ipynb
  examples/seismic/skew_self_adjoint/ssa_02_iso_implementation2.ipynb
  examples/seismic/skew_self_adjoint/ssa_03_iso_correctness.ipynb
Labels: documentation, examples

#1344 Freesurface with subdomain (iso-acoustic)
  .github/workflows/examples.yml
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/acoustic/operators.py
  examples/seismic/elastic/elastic_example.py
  examples/seismic/model.py
  examples/seismic/preset_models.py
  examples/seismic/skew_self_adjoint/example_iso.py
  examples/seismic/tti/tti_example.py
  examples/seismic/utils.py
  examples/seismic/viscoacoustic/viscoacoustic_example.py
  examples/seismic/viscoelastic/viscoelastic_example.py
Labels: POC, enhancement, examples

#1295 Fix MPI benchmark json results
  benchmarks/user/benchmark.py
  benchmarks/user/tools/driver.py
  benchmarks/user/tools/executor.py
  devito/operator/profiling.py
Labels: MPI

#1269 `ConditionalDimension`s notebook
  devito/__init__.py
  devito/types/relational.py
  examples/userapi/05_conditional_dimension.ipynb
  tests/test_dimension.py
  tests/test_operator.py
Labels: API, WIP, documentation, examples, good for newcomers

#1348 Refine CFL condition in seismic
  devito/types/basic.py
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/acoustic/operators.py
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/elastic/elastic_example.py
  examples/seismic/model.py
  examples/seismic/skew_self_adjoint/wavesolver.py
  examples/seismic/tutorials/06_elastic_varying_parameters.ipynb
  examples/seismic/tutorials/09_viscoelastic.ipynb
  examples/seismic/viscoacoustic/viscoacoustic_example.py
  examples/seismic/viscoelastic/viscoelastic_example.py
  examples/seismic/viscoelastic/wavesolver.py
  tests/test_symbolics.py
Labels: examples, minor-patch

#1359 Fix missing halo exchange over invariants fields
  devito/core/cpu.py
  devito/core/gpu_openacc.py
  devito/core/gpu_openmp.py
  devito/ir/clusters/analysis.py
  devito/ir/iet/nodes.py
  devito/ir/support/basic.py
  devito/ir/support/properties.py
  devito/ir/support/space.py
  devito/ir/support/vector.py
  devito/passes/iet/misc.py
  devito/passes/iet/mpi.py
  examples/compiler/03_iet-A.ipynb
  tests/test_ir.py
  tests/test_mpi.py
Labels: bug-C, compiler

#1349 Heapification of temporaries
  devito/base.py
  devito/core/cpu.py
  devito/core/gpu_openacc.py
  devito/core/gpu_openmp.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/mpi/routines.py
  devito/operator/__init__.py
  devito/operator/operator.py
  devito/operator/symbols.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/cse.py
  devito/passes/clusters/misc.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/passes/iet/misc.py
  devito/passes/iet/openmp.py
  devito/tools/utils.py
  devito/types/__init__.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dimension.py
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  examples/compiler/01_data_regions.ipynb
  examples/compiler/03_iet-A.ipynb
  examples/gpu/01_diffusion_with_openmp_offloading.ipynb
  tests/test_autotuner.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_ir.py
  tests/test_mpi.py
  tests/test_operator.py
  tests/test_pickle.py
Labels: better code, bug-C, compiler, enhancement

#1362 Symbolic speedup
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/sparse.py
  examples/cfd/06_poisson.ipynb
  examples/seismic/preset_models.py
  examples/seismic/tti/operators.py
  setup.cfg
  tests/test_dse.py
Labels: API, bug-performance-py, enhancement

#1360 Fix issue 1185
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  examples/cfd/02_convection_nonlinear.ipynb
  examples/cfd/03_diffusion.ipynb
  examples/cfd/03_diffusion_nonuniform.ipynb
  examples/cfd/04_burgers.ipynb
  examples/cfd/05_laplace.ipynb
  examples/cfd/06_poisson.ipynb
Labels: documentation, examples

#1367 examples: Drop unnecessary NBVALs
  examples/cfd/05_laplace.ipynb
  examples/cfd/06_poisson.ipynb
Labels: examples, minor-patch
