Repository devitocodes/devito, pull requests merged in 2020-03, with the labels that each got.

#1145 clean up dask tutorial
  examples/seismic/tutorials/04_dask.ipynb
Labels: documentation

#1153 Acoustic wavesolver: Specify stencil explicitly
  examples/seismic/acoustic/operators.py
Labels: testing

#1162 examples: Fix tti space_order setup
  examples/seismic/tti/tti_example.py
Labels: bug-py, minor-patch

#1178 tweak CI-gpu
  .github/azure/deployVM.ps1
  .github/workflows/pytest-gpu.yml
Labels: DevOps

#1190 Fixes issue #1128
  benchmarks/user/benchmark.py
Labels: low priority, minor-patch

#1191 ir: Fix placement of ArrayCasts from Conditionals
  devito/ir/iet/visitors.py
  devito/passes/iet/definitions.py
Labels: bug-py-minor

#1201 ShiftedDimension pickle fix
  devito/types/dimension.py
  tests/test_pickle.py
Labels: bug-py-minor
