Repository devitocodes/devito, pull requests merged in 2020-05, with the labels that each got.

#1247 FD for composite staggered expr
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/symbolics/manipulation.py
  devito/types/basic.py
  devito/types/caching.py
  devito/types/dense.py
  examples/cfd/02_convection_nonlinear.ipynb
  examples/cfd/06_poisson.ipynb
  tests/test_derivatives.py
  tests/test_staggered_utils.py
Labels: RFC, better code, bug-py, enhancement

#1264 Add support for AMD architectures
  devito/archinfo.py
  devito/compiler.py
Labels: RFC, WIP, enhancement, testing

#1279 Some cleanup
  README.md
  requirements.txt
Labels: upgrade_deps

#1278 Embed frozendict
  devito/ir/clusters/cluster.py
  devito/ir/support/space.py
  devito/mpi/halo_scheme.py
  devito/tools/data_structures.py
  devito/types/basic.py
  requirements.txt
Labels: upgrade_deps

#1270 ASV: only run on HEAD while caching all previous runs
  .github/workflows/asv.yml
  benchmarks/regression/merge_history.sh
Labels: DevOps, RFC

#1285 bench: Fix dumping in run mode with MPI
  benchmarks/user/benchmark.py
Labels: bug-py-minor

#1277 notebook tutorials for SSA isotropic
  examples/seismic/skew_self_adjoint/README.md
  examples/seismic/skew_self_adjoint/__init__.py
  examples/seismic/skew_self_adjoint/example_iso.py
  examples/seismic/skew_self_adjoint/operators.py
  examples/seismic/skew_self_adjoint/ssa_01_iso_implementation1.ipynb
  examples/seismic/skew_self_adjoint/ssa_02_iso_implementation2.ipynb
  examples/seismic/skew_self_adjoint/ssa_03_iso_correctness.ipynb
  examples/seismic/skew_self_adjoint/test_utils.py
  examples/seismic/skew_self_adjoint/test_wavesolver_iso.py
  examples/seismic/skew_self_adjoint/utils.py
  examples/seismic/skew_self_adjoint/wavesolver.py
Labels: documentation, enhancement

#1276 ConditionalDimension: Fix1273 inception
  devito/ir/clusters/algorithms.py
  devito/ir/equations/algorithms.py
  devito/operator/operator.py
  devito/types/__init__.py
  devito/types/relational.py
  tests/test_dimension.py
  tests/test_docstrings.py
  tests/test_operator.py
Labels: RFC, WIP, bug-py-minor, testing

#1291 Fix pickling with MPI full mode
  devito/core/gpu_openacc.py
  devito/mpi/routines.py
  devito/passes/iet/openmp.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/printer.py
  tests/test_pickle.py
Labels: bug-py, minor-patch

#1296 Expose CIRE knobs
  devito/core/cpu.py
  devito/core/gpu_openmp.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_mpi.py
Labels: enhancement, minor-patch

#1299 docs: Update index.rst and relative subpages
  README.md
  devito/types/dimension.py
  docs/source/compiler.rst
  docs/source/index.rst
  docs/source/tutorials.rst
  examples/README.md
Labels: documentation

#1300 Fix scheduling of dimension-invariant aliasing expressions
  devito/passes/clusters/aliases.py
  devito/types/dimension.py
  tests/test_dse.py
Labels: bug-py, minor-patch

#1317 deps: update for sympy 1.6
  devito/ir/equations/equation.py
  devito/types/caching.py
Labels: bug-py, upgrade_deps

#1307 Fix lowering of ConditionalDimensions Fix #1271
  devito/ir/iet/visitors.py
  tests/test_dimension.py
Labels: bug-py-minor, minor-patch

#1320 MPI overlap+: Fix offset identification
  devito/mpi/halo_scheme.py
  tests/test_mpi.py
  tests/test_subdomains.py
Labels: bug-py

#1310 WIP-RFC: Nested indexification Fix for #1283
  devito/ir/equations/algorithms.py
  tests/test_operator.py
Labels: bug-py-minor, minor-patch

#1304 Update seismic examples
  .github/workflows/examples.yml
  examples/cfd/03_diffusion.ipynb
  examples/seismic/acoustic/accuracy.ipynb
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/elastic/elastic_example.py
  examples/seismic/elastic/operators.py
  examples/seismic/elastic/wavesolver.py
  examples/seismic/inversion/fwi.py
  examples/seismic/model.py
  examples/seismic/preset_models.py
  examples/seismic/skew_self_adjoint/__init__.py
  examples/seismic/skew_self_adjoint/example_iso.py
  examples/seismic/skew_self_adjoint/operators.py
  examples/seismic/skew_self_adjoint/test_wavesolver_iso.py
  examples/seismic/skew_self_adjoint/utils.py
  examples/seismic/skew_self_adjoint/wavesolver.py
  examples/seismic/tti/operators.py
  examples/seismic/tti/tti_example.py
  examples/seismic/tti/wavesolver.py
  examples/seismic/tutorials/06_elastic_varying_parameters.ipynb
  examples/seismic/tutorials/07_DRP_schemes.ipynb
  examples/seismic/tutorials/08_snapshotting.ipynb
  examples/seismic/tutorials/09_viscoelastic.ipynb
  examples/seismic/tutorials/11_viscoacoustic.ipynb
  examples/seismic/utils.py
  examples/seismic/viscoacoustic/operators.py
  examples/seismic/viscoacoustic/viscoacoustic_example.py
  examples/seismic/viscoacoustic/wavesolver.py
  examples/seismic/viscoelastic/operators.py
  examples/seismic/viscoelastic/viscoelastic_example.py
  examples/seismic/viscoelastic/wavesolver.py
  examples/userapi/03_subdomains.ipynb
  tests/test_dse.py
  tests/test_tti.py
Labels: RFC, enhancement, good for newcomers
