Repository devitocodes/devito, pull requests merged in 2020-04, with the labels that each got.

#1203 Remove YASK and OPS backends
  .github/workflows/pytest-ops.yml
  .github/workflows/pytest-yask.yml
  benchmarks/user/benchmark.py
  devito/__init__.py
  devito/backends.py
  devito/builtins.py
  devito/logger.py
  devito/ops/__init__.py
  devito/ops/compiler.py
  devito/ops/node_factory.py
  devito/ops/operator.py
  devito/ops/transformer.py
  devito/ops/types.py
  devito/ops/utils.py
  devito/yask/__init__.py
  devito/yask/data.py
  devito/yask/operator.py
  devito/yask/transformer.py
  devito/yask/types.py
  devito/yask/utils.py
  devito/yask/wrappers.py
  examples/seismic/model.py
  tests/test_adjoint.py
  tests/test_autotuner.py
  tests/test_benchmark.py
  tests/test_builtins.py
  tests/test_caching.py
  tests/test_checkpointing.py
  tests/test_constant.py
  tests/test_data.py
  tests/test_derivatives.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_docstrings.py
  tests/test_dse.py
  tests/test_environment.py
  tests/test_gpu_openmp.py
  tests/test_gradient.py
  tests/test_interpolation.py
  tests/test_ir.py
  tests/test_mpi.py
  tests/test_operator.py
  tests/test_ops.py
  tests/test_pickle.py
  tests/test_resample.py
  tests/test_save.py
  tests/test_staggered_utils.py
  tests/test_subdomains.py
  tests/test_symbolic_coefficients.py
  tests/test_timestepping.py
  tests/test_tools.py
  tests/test_tti.py
  tests/test_visitors.py
  tests/test_yask.py
Labels: next

#1179 Add OpenACC testing to CI Fixes: #1168
  .github/workflows/pytest-gpu.yml
Labels: DevOps, GPUs

#1205 OpenACC inception
  .github/workflows/examples.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  .github/workflows/tutorials.yml
  benchmarks/user/README.md
  benchmarks/user/benchmark.py
  benchmarks/user/make-pbs.py
  devito/__init__.py
  devito/archinfo.py
  devito/compiler.py
  devito/core/__init__.py
  devito/core/cpu.py
  devito/core/gpu_openacc.py
  devito/core/gpu_openmp.py
  devito/core/operator.py
  devito/operator/operator.py
  devito/operator/registry.py
  devito/parameters.py
  devito/passes/iet/openmp.py
  docker-compose.yml
  docker/Dockerfile
  examples/compiler/01_data_regions.ipynb
  examples/compiler/03_iet-A.ipynb
  examples/mpi/overview.ipynb
  scripts/advisor/run_advisor.py
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_mpi.py
  tests/test_operator.py
Labels: GPUs

#1202 Speed up compilation
  devito/core/autotuning.py
  devito/core/cpu.py
  devito/core/gpu_openmp.py
  devito/core/operator.py
  devito/finite_differences/__init__.py
  devito/finite_differences/coefficients.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/finite_differences/lazy.py
  devito/finite_differences/tools.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/analysis.py
  devito/ir/clusters/queue.py
  devito/ir/equations/equation.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/ir/support/basic.py
  devito/ir/support/space.py
  devito/ir/support/utils.py
  devito/ir/support/vector.py
  devito/operations/interpolators.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/blocking.py
  devito/passes/clusters/cse.py
  devito/passes/clusters/factorization.py
  devito/passes/clusters/misc.py
  devito/passes/clusters/utils.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/manipulation.py
  devito/symbolics/printer.py
  devito/symbolics/queries.py
  devito/tools/abc.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/equation.py
  devito/types/sparse.py
  devito/types/tensor.py
  tests/test_dse.py
  tests/test_operator.py
Labels: DevOps, better code, bug-performance-py, enhancement

#1213 Make fd shortcut callable
  devito/finite_differences/derivative.py
  devito/finite_differences/tools.py
  tests/test_derivatives.py
Labels: enhancement, minor-patch, upgrade_deps

#1216 Mpi subdomain sets
  devito/operator/operator.py
  devito/types/grid.py
  tests/test_subdomains.py
Labels: enhancement

#1217 Basic support for OpenACC + MPI
  devito/compiler.py
  devito/core/gpu_openacc.py
  devito/core/gpu_openmp.py
  devito/ir/iet/visitors.py
  devito/mpi/distributed.py
  devito/mpi/routines.py
  devito/passes/iet/definitions.py
  tests/test_gpu_openacc.py
  tests/test_mpi.py
Labels: GPUs, enhancement

#1224 Fix OOB access caused by CIRE
  devito/core/gpu_openacc.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/symbolics/manipulation.py
  tests/test_dse.py
Labels: bug-py

#1228 OpenACC-MPI testing in python3
  .github/workflows/pytest-gpu.yml
  devito/compiler.py
  tests/conftest.py
Labels: DevOps, minor-patch

#1229 indexify fix
  devito/operator/operator.py
  devito/types/basic.py
  tests/test_dimension.py
Labels: bug-py, minor-patch, testing

#1233 tests: enable bench testing out of conda envs
  tests/test_benchmark.py
Labels: minor-patch

#1235 Fix scheduling of CIRE-detected aliasing expressions
  devito/core/cpu.py
  devito/core/gpu_openmp.py
  devito/finite_differences/differentiable.py
  devito/ir/equations/equation.py
  devito/ir/support/space.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/factorization.py
  devito/passes/clusters/misc.py
  devito/symbolics/queries.py
  tests/test_dse.py
  tests/test_operator.py
Labels: better code, bug-py

#1236 Patch MPI-related merge_halospot pass + MFE
  devito/passes/iet/mpi.py
  tests/test_mpi.py
Labels: bug-py, minor-patch

#1212 Adjoint tti
  examples/seismic/tti/operators.py
  examples/seismic/tti/tti_example.py
  examples/seismic/tti/wavesolver.py
  tests/test_adjoint.py
Labels: documentation, enhancement, good for newcomers

#1231 ssa iso implementation
  examples/seismic/skew_self_adjoint/README.md
  examples/seismic/skew_self_adjoint/__init__.py
  examples/seismic/skew_self_adjoint/ssa_01_iso_implementation1.ipynb
  examples/seismic/skew_self_adjoint/testUtils.py
  examples/seismic/skew_self_adjoint/utils.py
Labels: RFC, WIP, documentation, enhancement

#1244 Fix incorrect Cluster fusion (aka loop fusion)
  devito/core/cpu.py
  devito/core/gpu_openmp.py
  devito/ir/clusters/algorithms.py
  devito/passes/clusters/misc.py
  examples/cfd/01_convection.ipynb
  tests/test_operator.py
Labels: bug-py

#1074 Airspeed velocity
  .coveragerc
  .github/workflows/asv.yml
  .github/workflows/pytest-core-nompi.yml
  README.md
  benchmarks/regression/README.md
  benchmarks/regression/asv.conf.json
  benchmarks/regression/benchmarks/__init__.py
  benchmarks/regression/benchmarks/acoustic.py
  benchmarks/regression/benchmarks/codegen.py
  benchmarks/regression/benchmarks/simple_operators.py
  benchmarks/regression/merge_history.sh
  examples/checkpointing/__init__.py
  examples/compiler/__init__.py
  examples/userapi/__init__.py
  setup.py
Labels: DevOps

#1256 ASV tweaks
  .github/workflows/asv.yml
  benchmarks/regression/benchmarks/acoustic.py
  benchmarks/regression/benchmarks/codegen.py
  benchmarks/regression/benchmarks/simple_operators.py
Labels: minor-patch

#1253 Use OpenMP static scheduling for loops with small operation count
  benchmarks/user/README.md
  devito/__init__.py
  devito/compiler.py
  devito/ir/clusters/cluster.py
  devito/operator/profiling.py
  devito/parameters.py
  devito/passes/iet/openmp.py
  tests/test_dle.py
  tests/test_mpi.py
Labels: bug-performance-C, bug-py-minor, minor-patch

#1258 profiling: Add gflopss to fdlike set of metrics
  devito/operator/profiling.py
Labels: minor-patch

#1259 bench: Return solver output from run() instead of just None
  benchmarks/user/benchmark.py
Labels: minor-patch

#1262 docs:fix Conditional type docs
  devito/types/dimension.py
  examples/seismic/tutorials/08_snapshotting.ipynb
Labels: documentation, minor-patch

#1263 jit: Smarter CustomCompiler
  devito/compiler.py
Labels: bug-performance-py, minor-patch

#1261 bench: Add --dump-summary option
  benchmarks/user/benchmark.py
Labels: minor-patch

#1257 Add `shape` option in examples
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/elastic/elastic_example.py
  examples/seismic/tti/tti_example.py
  examples/seismic/viscoacoustic/viscoacoustic_example.py
  examples/seismic/viscoelastic/viscoelastic_example.py
Labels: minor-patch
