Repository devitocodes/devito, pull requests merged in 2020-11, with the labels that each got.

#1487 Patch compilation time
  devito/ir/iet/visitors.py
  devito/tools/utils.py
  devito/types/basic.py
  tests/test_visitors.py
Labels: bug-performance-py, compiler, high priority, minor-patch

#1488 Patch issue #1477
  devito/passes/clusters/aliases.py
  tests/test_dse.py
Labels: bug-py-minor, compiler, minor-patch

#1489 Tensor grid fixup
  devito/passes/equations/linearity.py
  devito/types/basic.py
  devito/types/equation.py
  devito/types/tensor.py
  tests/test_exprs_lowering.py
  tests/test_tensors.py
Labels: API, bug-C, bug-py, compiler

#1499 Function globabl size method
  devito/types/dense.py
  tests/test_mpi.py
Labels: minor-patch

#1493 Outhalo size warning
  devito/types/dense.py
Labels: MPI

#1495 Fixup _drop_halospots
  devito/passes/iet/mpi.py
  tests/test_mpi.py
Labels: MPI, bug-C, compiler, minor-patch

#1492 Fix MPI in Dockerfile.nvidia
  .github/workflows/docker-publish.yml
  docker/Dockerfile
  docker/Dockerfile.nvidia
  requirements-mpi.txt
  requirements-optional.txt
  requirements.txt
Labels: GPUs, docker

#1496 Fixup _hoist_halospots
  devito/passes/iet/mpi.py
  tests/test_mpi.py
Labels: MPI, bug-C, compiler, minor-patch

#1494 Fix halo update hoisting
  devito/passes/iet/mpi.py
  tests/test_mpi.py
Labels: MPI, bug-C, compiler, minor-patch

#1470 Tidy gpu CI workflow
  .github/workflows/asv.yml
  .github/workflows/examples-mpi.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-gpu.yml
  devito/core/gpu_openmp.py
Labels: DevOps, GPUs

#1497 Fix custom coefficients on staggered grids
  devito/finite_differences/coefficients.py
  devito/symbolics/queries.py
  devito/symbolics/search.py
  tests/test_symbolic_coefficients.py
Labels: API, bug-py

#1505 ci: Disable dask tutos on OSX build
  .github/workflows/tutorials.yml
Labels: testing

#1504 ir: Fixup _lower_stepping_dims
  devito/ir/iet/scheduler.py
  tests/test_operator.py
Labels: bug-py-minor, compiler, minor-patch

#1511 builtins: initialize FD halo
  .github/workflows/tutorials.yml
  devito/builtins/__init__.py
  devito/builtins/arithmetic.py
  devito/builtins/initializers.py
  devito/builtins/utils.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/operators.py
  devito/passes/clusters/aliases.py
  devito/types/tensor.py
  tests/test_builtins.py
  tests/test_derivatives.py
Labels: API, MPI

#1514 Postpone lowering of Section into TimedList
  devito/core/autotuning.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/operator/operator.py
  devito/operator/profiling.py
  devito/passes/iet/__init__.py
  devito/passes/iet/instrument.py
  devito/passes/iet/openmp.py
  devito/types/__init__.py
  devito/types/misc.py
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  examples/compiler/01_data_regions.ipynb
  examples/compiler/03_iet-A.ipynb
  examples/performance/00_overview.ipynb
  examples/performance/01_gpu.ipynb
  tests/test_dle.py
  tests/test_operator.py
  tests/test_pickle.py
Labels: better code, compiler, enhancement, help wanted

#1507 make test tools less random
  tests/test_tools.py
Labels: DevOps

#1462 perf: Add global gflopss to operator log
  devito/operator/operator.py
Labels: minor-patch

#1517 Use omp_set_default_device for OpenMP GPU offloading
  devito/core/gpu_openmp.py
  examples/performance/01_gpu.ipynb
  tests/test_gpu_openmp.py
Labels: GPUs, WIP, better code

#1516 Fix profiling IET for Intel Advisor benchmarking
  devito/operator/profiling.py
Labels: low priority, minor-patch
