Repository devitocodes/devito, pull requests merged in 2021-02, with the labels that each got.

#1576 BoundSymbol constructor to be cached
  devito/types/basic.py
  tests/test_caching.py
Labels: API, bug-py, minor-patch

#1561 Shift argument as a tuple
  devito/finite_differences/differentiable.py
  devito/finite_differences/tools.py
  devito/types/tensor.py
  tests/test_derivatives.py
  tests/test_tensors.py
Labels: API

#1580 Fix hierarchical blocking + parallelism
  devito/passes/clusters/aliases.py
  devito/passes/clusters/blocking.py
  devito/types/dimension.py
  tests/test_dse.py
  tests/test_pickle.py
Labels: bug-C, compiler, minor-patch

#1562 Tutorials: add shift parameter to Ren visco-acoustic equation
  examples/seismic/tutorials/11_viscoacoustic.ipynb
Labels: examples

#1583 Refactor Array sharing
  devito/core/autotuning.py
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/clusters/cluster.py
  devito/ir/iet/nodes.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/ir/support/properties.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/iet/definitions.py
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/parpragma.py
  devito/types/array.py
  devito/types/parallel.py
  examples/performance/00_overview.ipynb
  examples/performance/README.md
  tests/test_dse.py
  tests/test_pickle.py
Labels: better code, compiler

#1584 Fix find_library issue to MacOS Big Sur
  devito/data/allocators.py
Labels: compiler, minor-patch

#1585 compiler: Improve the cost model used by CIRE
  devito/core/cpu.py
  devito/core/gpu.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/utils.py
  devito/symbolics/inspection.py
  examples/performance/00_overview.ipynb
  examples/performance/01_gpu.ipynb
  tests/test_dle.py
  tests/test_dse.py
  tests/test_gpu_common.py
Labels: bug-py, compiler

#1567 examples: add first order adjoint viscoacoustic equations
  examples/seismic/viscoacoustic/operators.py
  examples/seismic/viscoacoustic/wavesolver.py
  tests/test_adjoint.py
Labels: examples

#1555 examples: Born approximation for TTI media
  examples/seismic/tti/operators.py
  examples/seismic/tti/wavesolver.py
  tests/test_adjoint.py
  tests/test_gradient.py
Labels: examples

#1593 gpu: Updated Dockerfile.nvidia to HPC SDK 21.1
  docker/Dockerfile.nvidia
Labels: GPUs, docker

#1596 bench: Add dumpnorms to run-jit-backdoor mode
  benchmarks/user/README.md
  benchmarks/user/benchmark.py
Labels: enhancement

#1597 compiler: Patch issue #1592 (HaloScheme with time subdimensions)
  devito/mpi/halo_scheme.py
  tests/test_dimension.py
Labels: bug-py, compiler

#1606 misc: Patch ThreadID pickling
  devito/types/parallel.py
  tests/test_pickle.py
Labels: minor-patch
