Repository devitocodes/devito, pull requests merged in 2021-09, with the labels that each got.

#1745 bench: Patch jacobian operators + MPI (see issue #1744)
  benchmarks/user/benchmark.py
Labels: bug-py, benchmarking

#1748 mpi: Speedup index_glb_to_loc
  devito/data/decomposition.py
Labels: MPI

#1740 tests: add tti_setup to gradientJ test
  tests/test_gradient.py
Labels: examples

#1736 compiler: Add optimization option to fuse WithLocks tasks
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/iet/nodes.py
  devito/passes/clusters/misc.py
  devito/passes/iet/langbase.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/orchestration.py
  devito/passes/iet/parpragma.py
  tests/test_gpu_common.py
Labels: GPU

#1747 Examples: enforce stable space order for self adjoint op
  examples/seismic/self_adjoint/example_iso.py
Labels: bug-py-minor, examples

#1759 ci: Update Ubuntu versions
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/tutorials.yml
Labels: CI

#1760 install: Udpate to HPCSDK 21.7, Update to Jupyter>=3.0
  docker/Dockerfile.nvidia
  docker/Singularity.nvidia.def
  requirements-nvidia.txt
Labels: installation

#1757 compiler: Fix zero to zero slices
  devito/builtins/initializers.py
  devito/builtins/utils.py
  devito/data/data.py
  devito/data/decomposition.py
  tests/test_data.py
Labels: bug-py
