Repository devitocodes/devito, pull requests merged in 2021-03, with the labels that each got.

#1607 mpi: Pass MPI_COMM_SELF to Distributor upon unpickling
  devito/types/grid.py
  tests/test_pickle.py
Labels: MPI, minor-patch

#1609 mpi: Prevent double finalization with devito used as a lib
  devito/mpi/distributed.py
Labels: MPI, minor-patch

#1604 mpi: Add ability to specify MPI topology used for grid division
  devito/mpi/distributed.py
  devito/types/grid.py
  tests/test_mpi.py
Labels: MPI, minor-patch

#1612 misc: Avoid crashing on missing _memfree_args
  devito/data/data.py
Labels: bug-py, minor-patch

#1605 misc: Use pickled soname rather than generating a new one
  devito/operator/operator.py
Labels: minor-patch

#1608 dsl: Enable overriding over SubDimension thickness
  devito/types/dimension.py
  tests/test_dimension.py
Labels: API, minor-patch

#1595 dsl: Patch symbolic coefficients with staggered grids
  devito/finite_differences/coefficients.py
  devito/finite_differences/tools.py
  tests/test_symbolic_coefficients.py
Labels: bug-py

#1615 arch: Add nvidia-smi parser to GPU checking
  devito/arch/archinfo.py
  tests/test_gpu_common.py
Labels: GPUs, bug-py-minor, minor-patch

#1618 ci: Transfer gpu workflow to self-hosted runners
  .github/workflows/pytest-gpu.yml
Labels: DevOps, GPUs, WIP

#1587 compiler: Target gpu for PGI openacc
  devito/arch/compiler.py
  examples/seismic/viscoacoustic/viscoacoustic_example.py
Labels: GPUs, compiler

#1623 ci: Work around archives missing error on apt install
  .github/workflows/pytest-core-mpi.yml
Labels: WIP, testing

#1591 compiler: Add option to use Functions, in place of Arrays, for compiler-generated temporary
  .github/workflows/pytest-core-mpi.yml
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/ir/support/properties.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/iet/definitions.py
  devito/passes/iet/parpragma.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  examples/performance/00_overview.ipynb
  examples/performance/README.md
  examples/performance/__init__.py
  tests/test_dse.py
  tests/test_pickle.py
Labels: compiler

#1603 dsl: Add MatrixSparseTimeFunction to support multi-point sources
  devito/base.py
  devito/types/sparse.py
  tests/test_interpolation.py
  tests/test_msparse.py
Labels: API, enhancement, high priority

#1626 arch: Review get_gpu_info
  devito/arch/archinfo.py
  tests/test_gpu_common.py
Labels: GPUs, bug-py-minor

#1611 compiler: Fix ScheduleTree construction in presence of guards and/or syncs
  devito/core/__init__.py
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/stree/algorithms.py
  devito/ir/support/basic.py
  devito/ir/support/space.py
  devito/mpi/halo_scheme.py
  devito/symbolics/inspection.py
  examples/performance/README.md
  tests/test_dimension.py
  tests/test_dse.py
  tests/test_gpu_common.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_ir.py
  tests/test_mpi.py
Labels: bug-C, bug-py, compiler

#1628 compiler: Fix processing of grid spacing
  devito/operator/operator.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/grid.py
  devito/types/sparse.py
  tests/test_autotuner.py
  tests/test_caching.py
  tests/test_derivatives.py
  tests/test_dimension.py
  tests/test_interpolation.py
  tests/test_mpi.py
  tests/test_pickle.py
Labels: API, compiler

#1632 misc: Drop unused backend infrastructure
  benchmarks/user/benchmark.py
  devito/__init__.py
  devito/backends.py
  devito/base.py
  devito/core/__init__.py
  devito/parameters.py
  tests/conftest.py
Labels: compiler

#1630 mpi: Add diag2 mode
  devito/__init__.py
  devito/mpi/routines.py
  tests/conftest.py
  tests/test_mpi.py
Labels: MPI, testing

#1634 compiler: Work around clang[10,11,?] omp-offloading bug
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/passes/iet/definitions.py
  devito/passes/iet/langbase.py
  devito/passes/iet/languages/openmp.py
  examples/performance/01_gpu.ipynb
Labels: GPUs, compiler

#1635 ci: Update Ci-gpu for nvidia openmp
  .github/workflows/pytest-gpu.yml
Labels: CI, GPUs

#1631 compiler: Improve aliases detection, processing, and optimization
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/clusters/queue.py
  devito/ir/stree/algorithms.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/blocking.py
  devito/passes/clusters/misc.py
  devito/passes/clusters/utils.py
  devito/symbolics/inspection.py
  devito/symbolics/manipulation.py
  devito/symbolics/printer.py
  devito/symbolics/queries.py
  devito/symbolics/search.py
  examples/performance/00_overview.ipynb
  examples/performance/01_gpu.ipynb
  examples/performance/README.md
  tests/test_dse.py
  tests/test_gpu_openmp.py
  tests/test_mpi.py
  tests/test_symbolics.py
Labels: API, better code, bug-performance-C, compiler, enhancement
