Repository devitocodes/devito, pull requests merged in 2021-08, with the labels that each got.

#1727 compiler: Introduce linearization pass
  devito/core/arm.py
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/mpi/routines.py
  devito/passes/clusters/asynchrony.py
  devito/passes/clusters/utils.py
  devito/passes/iet/__init__.py
  devito/passes/iet/definitions.py
  devito/passes/iet/langbase.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/linearization.py
  devito/passes/iet/misc.py
  devito/passes/iet/mpi.py
  devito/passes/iet/orchestration.py
  devito/passes/iet/parpragma.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/manipulation.py
  devito/symbolics/printer.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dimension.py
  devito/types/misc.py
  devito/types/sparse.py
  examples/compiler/03_iet-A.ipynb
  examples/performance/00_overview.ipynb
  examples/performance/README.md
  examples/performance/utils.py
  tests/test_dse.py
  tests/test_gpu_common.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_iet.py
  tests/test_linearize.py
  tests/test_mpi.py
  tests/test_operator.py
Labels: compiler

#1734 reqs: enforce pip>=21.1.2 for conda env installation
  environment-dev.yml
Labels: dependencies, installation

#1731 compiler: improve HB generated code
  devito/passes/iet/misc.py
  examples/performance/00_overview.ipynb
Labels: compiler, bug-C-minor

#1732 compiler: Loop fission
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/clusters/algorithms.py
  devito/ir/support/space.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/misc.py
  devito/tools/abc.py
  tests/test_dse.py
  tests/test_fission.py
Labels: compiler

#1735 compiler: lift skewing in higher block levels
  devito/passes/clusters/blocking.py
  tests/test_skewing.py
Labels: compiler

#1742 bench: Add warmup option to run mode
  benchmarks/user/benchmark.py
Labels: benchmarking
