Repository devitocodes/devito, pull requests merged in 2021-04, with the labels that each got.

#1648 ci: Fix conda build
  .github/workflows/examples.yml
Labels: CI

#1651 ci: Switch to default gcc(9.3) for conda build
  .github/workflows/examples.yml
  .github/workflows/tutorials.yml
  devito/ir/iet/nodes.py
  devito/tools/__init__.py
  devito/tools/timing.py
Labels: CI

#1647 types: Drop unsafe/unnecessary memoization in the arguments processing engine
  benchmarks/regression/benchmarks/arguments.py
  devito/operator/operator.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/grid.py
  devito/types/sparse.py
Labels: CI, better code, bug-py, enhancement

#1649 advisor: merge roofline and json
  benchmarks/user/advisor/README.md
  benchmarks/user/advisor/advisor_to_json.py
  benchmarks/user/advisor/roofline.py
  benchmarks/user/advisor/run_advisor.py
Labels: low priority, minor-patch

#1645 gpu: Add gpu-fit value for all functions (fix #1642)
  .github/workflows/pytest-gpu.yml
  devito/core/gpu.py
  devito/passes/iet/misc.py
  tests/test_adjoint.py
Labels: GPUs, compiler, minor-patch

#1620 compiler: Add skewing pass towards Temporal Blocking
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/clusters/analysis.py
  devito/ir/clusters/cluster.py
  devito/ir/support/properties.py
  devito/passes/clusters/blocking.py
  examples/compiler/03_iet-A.ipynb
  examples/misc/linalg.py
  tests/conftest.py
  tests/test_autotuner.py
  tests/test_dimension.py
  tests/test_skewing.py
  tests/test_subdomains.py
Labels: compiler

#1617 examples: Add viscoacoustic Born operator to 2nd sls equation
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/elastic/wavesolver.py
  examples/seismic/tti/wavesolver.py
  examples/seismic/viscoacoustic/operators.py
  examples/seismic/viscoacoustic/wavesolver.py
  examples/seismic/viscoelastic/wavesolver.py
  tests/test_adjoint.py
  tests/test_gradient.py
  tests/test_tti.py
Labels: examples

#1602 examples: TTI 1st order operators
  examples/seismic/tti/operators.py
  examples/seismic/tti/tti_example.py
  examples/seismic/tti/wavesolver.py
  tests/test_adjoint.py
  tests/test_autotuner.py
  tests/test_dse.py
  tests/test_gradient.py
Labels: WIP, examples

#1650 compiler: Singletonize special symbols (e.g. nthreads)
  devito/builtins/arithmetic.py
  devito/core/operator.py
  devito/ir/iet/efunc.py
  devito/operations/interpolators.py
  devito/operator/symbols.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/cse.py
  devito/passes/clusters/factorization.py
  devito/passes/clusters/misc.py
  devito/passes/iet/engine.py
  devito/passes/iet/parpragma.py
  devito/symbolics/queries.py
  devito/symbolics/search.py
  devito/types/basic.py
  devito/types/parallel.py
  devito/types/sparse.py
  examples/seismic/viscoacoustic/wavesolver.py
  tests/test_caching.py
  tests/test_dle.py
  tests/test_gpu_common.py
  tests/test_pickle.py
Labels: compiler, enhancement

#1658 gpu: Fix leaks due to excessive fetching/prefetching
  devito/passes/clusters/asynchrony.py
  devito/passes/iet/orchestration.py
  devito/types/parallel.py
  tests/test_gpu_common.py
Labels: GPUs, bug-C, compiler, high priority, testing

#1663 ci: Re-enable adjoint tests
  tests/conftest.py
Labels: CI, minor-patch

#1661 ci: Drop obsolete DEVITO_BACKEND env var
  .github/workflows/examples-mpi.yml
  .github/workflows/examples.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/tutorials.yml
Labels: CI, minor-patch

#1664 ci: Modify mpi-example workflow and update docker actions
  .github/workflows/docker-publish.yml
  .github/workflows/examples-mpi.yml
Labels: CI

#1666 deps: fix py-cpuinfo
  requirements.txt
Labels: dependencies, minor-patch

#1659 gpu: Update Dockerfile.nvidia to HPC SDK 21.3
  docker/Dockerfile.nvidia
Labels: GPUs, docker

#1667 compiler: Check consistency between shape and grid for TimeFunction, too
  devito/types/dense.py
  tests/test_mpi.py
Labels: API, MPI

#1672 bench: Patch ASV's generation of new plots
  .gitignore
  benchmarks/regression/benchmarks/arguments.py
Labels: CI

#1669 compiler: Tweak nested-par candidate condition
  devito/passes/iet/parpragma.py
  tests/test_dle.py
Labels: compiler, low priority

#1677 compiler: Patch TempFunction pickling
  devito/types/dense.py
  tests/test_pickle.py
Labels: compiler, high priority, minor-patch

#1678 gpu: Fixup prefetch jitting when using extra symbols
  devito/passes/iet/orchestration.py
  tests/test_gpu_common.py
Labels: bug-C, compiler, high priority, minor-patch

#1679 misc: Fix clear-cache script
  scripts/clear_devito_cache.py
Labels: minor-patch

#1683 gpu: Patch selection of streamed TimeFunctions
  devito/passes/iet/misc.py
Labels: GPUs

#1684 gpu: Fix offloading when zero-size arrays
  devito/passes/iet/parpragma.py
  devito/types/sparse.py
  tests/test_gpu_common.py
Labels: GPUs

#1657 compiler: Improve derivative factorization pass
  devito/finite_differences/derivative.py
  devito/passes/equations/linearity.py
  devito/symbolics/manipulation.py
  tests/test_dse.py
  tests/test_lower_exprs.py
  tests/test_symbolics.py
Labels: compiler
