Repository devitocodes/devito, pull requests merged in 2021-11, with the labels that each got.

#1789 compiler: Nested indexification
  devito/ir/equations/algorithms.py
  devito/types/basic.py
  examples/seismic/tutorials/14_creating_synthetics.ipynb
  tests/test_operator.py
Labels: compiler

#1790 mpi: Add MPI support for python3.9
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  devito/data/data.py
  tests/test_data.py
Labels: MPI, CI

#1795 ci: add python 3.10, gcc-10 option
  .github/workflows/examples.yml
  .github/workflows/pytest-core-nompi.yml
  devito/arch/compiler.py
Labels: dependencies

#1796 compiler: Further minor tweaks
  devito/ir/iet/nodes.py
  devito/ir/support/basic.py
  devito/ir/support/utils.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/printer.py
  tests/test_pickle.py
Labels: compiler

#1793 compiler: Move lambda level to IncrDimension property
  devito/passes/clusters/blocking.py
  devito/types/dimension.py
Labels: compiler
