Repository devitocodes/devito, pull requests merged in 2021-05, with the labels that each got.

#1685 Update release-drafter.yml
  .github/release-drafter.yml
Labels: CI

#1687 testing: Patch expected output for ipython==7.23.0
  examples/seismic/self_adjoint/sa_01_iso_implementation1.ipynb
  examples/seismic/tutorials/03_fwi.ipynb
Labels: testing

#1686 bench: Fix asv new benchmark issue
  .github/workflows/asv.yml
  .gitignore
Labels: CI, benchmarking

#1689 Allow asv workflow to discover new benchmarks
  .github/workflows/asv.yml
Labels: CI, benchmarking

#1691 API: fixed callback of PrecomputedInterpolator injection
  devito/operations/interpolators.py
  tests/test_interpolation.py
Labels: bug-py

#1574 examples: Add LSRTM acoustic notebook
  examples/seismic/tutorials/13_LSRTM_acoustic.ipynb
Labels: examples

#1698 examples: Tweak LSRTM_acoustic notebook
  examples/seismic/tutorials/13_LSRTM_acoustic.ipynb
Labels: examples
