Repository devitocodes/devito, pull requests merged in 2021-01, with the labels that each got.

#1531 Migrate MPI CI
  .github/workflows/pytest-core-mpi.yml
Labels: testing

#1543 Move mpi examples to new runner
  .github/workflows/examples-mpi.yml
Labels: testing

#1530 Migrate asv workflow to new runner
  .github/workflows/asv.yml
  benchmarks/regression/asv.conf.json
Labels: testing

#1545 Fix docker ci
  .github/workflows/docker-publish.yml
Labels: docker, testing

#1502 Updated cavity flow notebook for cfd examples
  examples/cfd/07_cavity_flow.ipynb
Labels: examples

#1547 Refactor and enhance section profiling
  devito/core/autotuning.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/mpi/routines.py
  devito/operator/operator.py
  devito/operator/profiling.py
  devito/passes/iet/engine.py
  devito/passes/iet/instrument.py
  devito/passes/iet/misc.py
  devito/passes/iet/orchestration.py
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  examples/compiler/01_data_regions.ipynb
  examples/compiler/03_iet-A.ipynb
  examples/performance/00_overview.ipynb
  examples/performance/01_gpu.ipynb
  tests/test_gpu_openacc.py
  tests/test_mpi.py
  tests/test_operator.py
Labels: API, compiler, enhancement

#1406 Example: add second-order viscoacoustic equations
  examples/seismic/preset_models.py
  examples/seismic/viscoacoustic/operators.py
  examples/seismic/viscoacoustic/viscoacoustic_example.py
  examples/seismic/viscoacoustic/wavesolver.py
  tests/test_adjoint.py
Labels: examples

#1559 Skip viscoacoustic tests with openacc
  examples/seismic/viscoacoustic/viscoacoustic_example.py
Labels: GPUs, testing

#1544 operator: Use FD-Gpts/s instead of Gpts/s
  benchmarks/user/benchmark.py
  devito/operator/operator.py
  devito/operator/profiling.py
  examples/userapi/05_conditional_dimension.ipynb
Labels: better code, minor-patch

#1564 Bump static release number
  docs/source/conf.py
Labels: documentation

#1563 Introduce devito/arch
  benchmarks/user/benchmark.py
  devito/__init__.py
  devito/arch/__init__.py
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/core/__init__.py
  devito/core/autotuning.py
  devito/operator/operator.py
  devito/operator/registry.py
  tests/conftest.py
  tests/test_gpu_common.py
Labels: RFC, question

#1556 Data streaming support with OpenMP offloading
  devito/core/gpu_openmp.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/ir/support/utils.py
  devito/operator/operator.py
  devito/operator/symbols.py
  devito/passes/iet/definitions.py
  devito/passes/iet/orchestration.py
  devito/tools/utils.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/misc.py
  devito/types/sync.py
  tests/test_gpu_common.py
  tests/test_gpu_openacc.py
  tests/test_iet.py
  tests/test_pickle.py
Labels: GPUs, better code, compiler, enhancement, high priority

#1569 Introduce `deviceid` API to offload Operators on specific GPUs
  devito/core/gpu_openacc.py
  devito/core/gpu_openmp.py
  devito/mpi/distributed.py
  devito/operator/operator.py
  devito/operator/symbols.py
  devito/types/__init__.py
  devito/types/parallel.py
  examples/performance/01_gpu.ipynb
  tests/test_gpu_common.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_pickle.py
Labels: API, compiler, enhancement, high priority

#1572 Separate adjoint based tests
  .github/workflows/pytest-core-nompi.yml
Labels: DevOps

#1571 gpu: Add `devicerm` API for conditional deletions
  devito/core/gpu_openacc.py
  devito/core/gpu_openmp.py
  devito/types/parallel.py
  examples/performance/01_gpu.ipynb
  tests/test_gpu_common.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
Labels: API, GPUs, compiler
