Repository devitocodes/devito, pull requests merged in 2021-10, with the labels that each got.

#1762 compiler: Patch and improve SubDomainSet
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/clusters/algorithms.py
  devito/ir/equations/algorithms.py
  devito/ir/support/space.py
  devito/ir/support/utils.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/misc.py
  devito/types/grid.py
  tests/test_dse.py
  tests/test_subdomains.py
Labels: bug-performance-C, bug-C

#1764 compiler: Add machinery for custom memory allocators and MPI
  devito/core/arm.py
  devito/core/cpu.py
  devito/core/gpu.py
  devito/data/allocators.py
  devito/mpi/routines.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/passes/iet/mpi.py
  devito/types/grid.py
Labels: compiler

#1767 compiler: Patch SubDomainSet with NVC
  devito/types/grid.py
  tests/test_gpu_common.py
Labels: bug-C

#1768 mpi: Patch neighborhood construction
  devito/mpi/distributed.py
Labels: bug-py

#1769 sympy: proper version check
  devito/finite_differences/elementary.py
  examples/seismic/acoustic/wavesolver.py
Labels: API
