Repository devitocodes/devito, pull requests merged in 2022-12, with the labels that each got.

#2041 compiler: Introduce int32 mode
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/ir/iet/visitors.py
  devito/passes/iet/linearization.py
  devito/types/dense.py
  examples/compiler/04_iet-B.ipynb
  tests/test_linearize.py
  tests/test_visitors.py
Labels: compiler

#2040 ci: improve accuracy of codecov.
  codecov.yml
Labels: CI

#2005 dependencies: sympy 1.11 compatibility
  .github/workflows/pytest-core-nompi.yml
  devito/symbolics/printer.py
  requirements.txt
Labels: bug-py-minor, dependencies
