Repository devitocodes/devito, pull requests merged in 2022-03, with the labels that each got.

#1849 arch: Add lineinfo compiler flag
  devito/arch/compiler.py
Labels: arch

#1853 misc: Documentation tweaks
  README.md
  docs/source/conf.py
Labels: documentation

#1850 arch: Fix CustomCompiler instantiation
  devito/arch/compiler.py
Labels: arch

#1843 api: Add op.cinterface for C-level interoperability
  devito/ir/iet/visitors.py
  devito/operator/operator.py
  tests/test_cinterface.py
Labels: API

#1855 Fix 2D Gzz when sintheta==0
  examples/seismic/tti/operators.py
Labels: examples

#1854 install: Fix cflag for nvidia mpi4py
  docker/Dockerfile.nvidia
Labels: installation

#1861 compiler: Patch norm enforcing double precision accumulation
  devito/builtins/arithmetic.py
  devito/ir/clusters/cluster.py
  tests/test_builtins.py
Labels: bug-C

#1858 sympy: new version compat
  .github/workflows/pytest-core-nompi.yml
  devito/finite_differences/differentiable.py
  requirements.txt
Labels: dependencies

#1864 compiler: Patch norm accumulation
  devito/builtins/arithmetic.py
  devito/builtins/utils.py
  tests/test_builtins.py
Labels: bug-py

#1840 compiler: Add SEPARABLE property
  devito/core/cpu.py
  devito/ir/support/properties.py
  devito/ir/support/space.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/misc.py
  devito/symbolics/printer.py
  devito/types/misc.py
  tests/test_dse.py
Labels: compiler

#1865 compiler: Relax Data.__array_finalize__ to work with subclasses
  devito/data/data.py
Labels: compiler

#1868 compiler: Flip par-tile unrolling
  devito/passes/clusters/blocking.py
  tests/test_dle.py
Labels: compiler

#1870 compiler: Add GuardOverflow
  devito/ir/support/guards.py
  tests/test_ir.py
Labels: compiler

#1871 compiler: Drop unnecessary check_indices
  devito/types/basic.py
Labels: compiler

#1874 mpi: Do not send padding region when doing pythonland halo exchange
  devito/types/dense.py
  tests/conftest.py
  tests/test_mpi.py
Labels: MPI

#1873 tests: Add MFE for issue 1753
  tests/test_dimension.py
Labels: testing

#1872 compiler: Move derivative.evaluate
  devito/finite_differences/derivative.py
  devito/finite_differences/finite_difference.py
Labels: compiler

#1878 compiler: Do not evaluate unevaluable expressions
  devito/finite_differences/differentiable.py
  tests/test_lower_exprs.py
Labels: bug-py-minor

#1880 compiler: Avoid generating unnecessary conditionals
  devito/passes/iet/parpragma.py
Labels: compiler

#1845 compiler: Minor blocking.py refactorings
  devito/data/utils.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/analysis.py
  devito/ir/support/space.py
  devito/passes/clusters/blocking.py
  devito/passes/clusters/buffering.py
  examples/seismic/tti/tti_example.py
  tests/test_interpolation.py
  tests/test_operator.py
Labels: compiler

#1882 compiler: Drop ARM specialization
  devito/core/arm.py
  devito/core/cpu.py
  devito/passes/iet/misc.py
  tests/test_operator.py
Labels: arch
