Repository devitocodes/devito, pull requests merged in 2022-10, with the labels that each got.

#2011 types: Minor fixes to sparse function indices and implicit dims
  devito/operations/interpolators.py
  devito/types/sparse.py
  tests/test_interpolation.py
Labels: bug-py-minor

#2013 ci: Remove docker pruning from pytest-gpu
  .github/workflows/pytest-gpu.yml
Labels: testing

#2012 compiler: Further misc improvements
  devito/builtins/initializers.py
  devito/builtins/utils.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/operator/operator.py
  devito/passes/iet/asynchrony.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/passes/iet/langbase.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/linearization.py
  devito/passes/iet/parpragma.py
  devito/tools/data_structures.py
  devito/types/dimension.py
  devito/types/misc.py
  devito/types/parallel.py
  examples/compiler/03_iet-A.ipynb
  examples/compiler/04_iet-B.ipynb
  tests/test_builtins.py
  tests/test_derivatives.py
  tests/test_dimension.py
Labels: compiler

#1998 Examples: Add Darcy flow example
  examples/cfd/09_Darcy_flow_equation.ipynb
Labels: examples

#2018 symbolics: Fix absolute value warning for integer input
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/tutorials.yml
  devito/ir/iet/visitors.py
  devito/operator/operator.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/printer.py
  tests/test_symbolics.py
Labels: bug-py-minor

#2010 Update FAQ.md
  FAQ.md
Labels: documentation

#2017 ci: Remove dangling docker layers
  .github/workflows/docker-devito.yml
  .github/workflows/pytest-gpu.yml
Labels: CI

#2020 compiler: Better blocking heuristics and revamped linearization
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/cluster.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/ir/support/properties.py
  devito/ir/support/space.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/blocking.py
  devito/passes/clusters/buffering.py
  devito/passes/clusters/cse.py
  devito/passes/iet/engine.py
  devito/passes/iet/linearization.py
  devito/passes/iet/misc.py
  devito/types/basic.py
  devito/types/misc.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_linearize.py
Labels: compiler
