Repository devitocodes/devito, pull requests merged in 2022-07, with the labels that each got.

#1946 install: Create scheduled base docker images for better build
  .github/workflows/docker-bases.yml
  .github/workflows/docker-devito.yml
  .github/workflows/docker-publish.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  .github/workflows/tutorials.yml
  README.md
  devito/arch/compiler.py
  devito/core/gpu.py
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile.amd
  docker/Dockerfile.cpu
  docker/Dockerfile.devito
  docker/Dockerfile.nvidia
  docker/README.md
  docker/entrypoint.sh
  examples/performance/01_gpu.ipynb
  tests/conftest.py
  tests/test_dle.py
  tests/test_gpu_common.py
  tests/test_gpu_openmp.py
  tests/test_gradient.py
Labels: testing, GPU, dependencies, CI, installation

#1948 compiler: Support interpolation with user-provided implicit dims
  devito/operations/interpolators.py
  devito/types/sparse.py
  tests/test_dimension.py
Labels: API

#1938 compiler: Decouple pthreading pass from orchestration
  devito/builtins/arithmetic.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/ir/clusters/cluster.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/iet/utils.py
  devito/ir/support/__init__.py
  devito/ir/support/syncs.py
  devito/passes/clusters/asynchrony.py
  devito/passes/clusters/implicit.py
  devito/passes/clusters/misc.py
  devito/passes/iet/__init__.py
  devito/passes/iet/asynchrony.py
  devito/passes/iet/engine.py
  devito/passes/iet/langbase.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/orchestration.py
  devito/passes/iet/parpragma.py
  devito/symbolics/extended_sympy.py
  devito/types/parallel.py
  tests/test_gpu_common.py
  tests/test_gpu_openacc.py
  tests/test_pickle.py
Labels: compiler

#1942 api: Fix Derivative substitution
  devito/finite_differences/derivative.py
  tests/test_derivatives.py
Labels: bug-py-minor

#1947 mpi: Fix data distribution bugs [part 1]
  devito/data/data.py
  devito/data/utils.py
  tests/test_data.py
Labels: bug-py, MPI

#1961 install: Update to intel-oneapi-mpi-devel
  docker/Dockerfile.cpu
Labels: CI

#1960 tests: Refactor conftest skipif names
  docker/README.md
  tests/conftest.py
  tests/test_buffering.py
  tests/test_dle.py
  tests/test_gradient.py
Labels: testing

#1958 compiler: Remove IndexedData.free_symbols hack
  devito/types/basic.py
  examples/performance/00_overview.ipynb
  tests/test_symbolics.py
Labels: compiler

#1977 compiler: Restructure basic.Object sub-hierarchy
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/passes/iet/definitions.py
  devito/types/__init__.py
  devito/types/basic.py
  devito/types/object.py
  tests/test_iet.py
Labels: compiler
