Repository devitocodes/devito, pull requests merged in 2022-11, with the labels that each got.

#2028 ci: Streamlining
  .github/workflows/docker-bases.yml
  .github/workflows/docker-devito.yml
  .github/workflows/pytest-gpu.yml
Labels: CI

#2030 misc: Add packages to Docker base images
  .github/workflows/docker-bases.yml
  .github/workflows/documentation.yml
  .github/workflows/pytest-gpu.yml
  docker/Dockerfile.amd
  docker/Dockerfile.cpu
  docker/Dockerfile.nvidia
Labels: installation

#2033 compiler: Ensure order invariance of candidates in ReducerMap.unique
  devito/tools/data_structures.py
Labels: bug-py-minor

#1972 misc: Update docker/README.md
  CONTRIBUTING.md
  FAQ.md
  README.md
  docker-compose.yml
  docker/README.md
  docker/entrypoint.sh
  docs/source/download.rst
  examples/seismic/source.py
  examples/seismic/utils.py
Labels: documentation

#2035 ci: Add Arm skip option to tests
  docs/source/download.rst
  tests/conftest.py
  tests/test_autotuner.py
  tests/test_dse.py
Labels: bug-py-minor

#2037 docs: Update compiler summary image
  examples/compiler/00_index.ipynb
Labels: documentation
