Repository devitocodes/devito, pull requests merged in 2022-05, with the labels that each got.

#1916 compiler: Patch buffer initialization
  devito/passes/clusters/buffering.py
  tests/test_buffering.py
Labels: bug-C

#1922 compiler: Patch fission (issue 1921)
  devito/ir/support/space.py
  devito/passes/clusters/misc.py
  tests/test_fission.py
Labels: bug-py

#1913 compiler: Uncache data carriers
  devito/types/basic.py
  devito/types/caching.py
  examples/compiler/04_iet-B.ipynb
  examples/performance/01_gpu.ipynb
  tests/test_caching.py
Labels: compiler

#1899 deps: Drop deprecated distutils imports
  devito/arch/compiler.py
  devito/core/gpu.py
  devito/finite_differences/elementary.py
  devito/passes/iet/languages/openmp.py
  versioneer.py
Labels: dependencies
