Repository devitocodes/devito, pull requests merged in 2022-02, with the labels that each got.

#1832 benchmarks: custom click type for grid params
  benchmarks/user/benchmark.py
  examples/misc/linalg.py
  requirements.txt
Labels: dependencies

#1697 compiler: Fixes #1695 by prioritising innermost vectorizable candidates
  devito/passes/iet/parpragma.py
  tests/test_dle.py
  tests/test_dse.py
Labels: bug-C-minor

#1835 misc: Add requirements.txt and requirements-optional.txt to MANIFEST.in
  MANIFEST.in
Labels: installation

#1824 mpi: Fix mask ordering for sparse gather
  .github/workflows/pytest-core-mpi.yml
  devito/types/sparse.py
  tests/test_gpu_common.py
  tests/test_mpi.py
Labels: MPI

#1820 examples: Add nonzero example to ConditionalDimension tutorial
  examples/userapi/05_conditional_dimension.ipynb
Labels: examples

#1836 gpu: Adding DPCPP compiler support
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/passes/iet/languages/openmp.py
Labels: GPU

#1839 compiler: Patch linearization pass
  devito/passes/iet/linearization.py
  tests/test_linearize.py
Labels: bug-C

#1841 compiler: Use int64_t, not unsigned int, for linearization
  devito/passes/iet/linearization.py
  tests/test_linearize.py
Labels: bug-C

#1842 [nvidia,gpu] Update to HPC SDK 22.2 and CUDA 11.6
  docker/Dockerfile.nvidia
  docker/Singularity.nvidia.def
Labels: GPU

#1844 CI: prevent conflict with pytest
  requirements.txt
  tests/conftest.py
  tests/test_gradient.py
Labels: testing

#1848 misc: Add citation button
  CITATION.md
Labels: documentation

#1847 Installation: update setup.py and cleanup docker files
  .github/workflows/pytest-core-mpi.yml
  docker/Dockerfile
  docker/Dockerfile.nvidia
  docker/entrypoint.sh
  docker/run-jupyter.sh
  docker/run-jupyterlab.sh
  docker/run-print-defaults.sh
  docker/run-tests.sh
  setup.py
Labels: installation

#1852 install: Fix EOL typo
  docker/Dockerfile
  docker/Dockerfile.nvidia
Labels: installation
