Repository devitocodes/devito, pull requests merged in 2022-08, with the labels that each got.

#1979 compiler: Patch premature lowering of EvalDerivative
  devito/finite_differences/differentiable.py
  setup.cfg
  tests/test_derivatives.py
  tests/test_dse.py
Labels: bug-performance-py

#1982 docker: Fix docker tags for publish
  .github/workflows/docker-devito.yml
  .github/workflows/pytest-gpu.yml
Labels: installation

#1975 install: Patch Dockerfile.nvidia
  docker/Dockerfile.nvidia
Labels: installation

#1980 compiler: Generalize lowering of reductions
  .github/workflows/docker-devito.yml
  devito/core/cpu.py
  devito/core/gpu.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/analysis.py
  devito/ir/clusters/cluster.py
  devito/passes/clusters/factorization.py
  devito/passes/clusters/utils.py
  devito/symbolics/extended_sympy.py
Labels: compiler

#1985 docker: fix deployment condition
  .github/workflows/docker-devito.yml
Labels: CI

#1976 misc: Add FAQ page (lifted from the wiki)
  FAQ.md
  README.md
Labels: documentation

#1983 compiler: Check jit_dir existence when saving
  devito/arch/compiler.py
Labels: bug-py-minor

#1914 examples: invoke tti example with --constant argument
  examples/seismic/acoustic/acoustic_example.py
  examples/seismic/model.py
  examples/seismic/preset_models.py
  examples/seismic/tti/tti_example.py
  examples/seismic/tutorials/15_tti_qp_pure.ipynb
  tests/test_tti.py
Labels: examples

#1867 examples: Add shallow water equations notebook
  examples/cfd/08_shallow_water_equation.ipynb
  examples/cfd/images/shallow_water_sketch.png
Labels: examples

#1984 compiler: Misc tweaks for backend-portable code generation
  devito/arch/compiler.py
  devito/core/gpu.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/passes/__init__.py
  devito/passes/clusters/blocking.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/passes/iet/langbase.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/misc.py
  devito/passes/iet/orchestration.py
  devito/types/basic.py
  devito/types/object.py
  tests/test_autotuner.py
  tests/test_caching.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_subdomains.py
Labels: compiler

#1992 compiler: Fix MPI mode diag2 does not need a MPIRegion
  devito/mpi/routines.py
Labels: MPI
