Repository devitocodes/devito, pull requests merged in 2022-06, with the labels that each got.

#1923 examples: Update MPI tutorial notebook and scripts
  .github/workflows/examples-mpi.yml
  examples/mpi/overview.ipynb
  requirements-mpi.txt
  requirements-optional.txt
  scripts/create_ipyparallel_mpi_profile.sh
Labels: examples

#1929 compiler: Add blockrelax tests and refresh advisor profiling
  benchmarks/user/advisor/run_advisor.py
  devito/core/autotuning.py
  examples/misc/linalg.py
  tests/test_dle.py
Labels: benchmarking

#1931 arch: Support OpenMP on Apple M1
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/tools/memoization.py
Labels: arch

#1893 compiler: Inception of two-stage derivative evaluation
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/elementary.py
  devito/finite_differences/finite_difference.py
  devito/finite_differences/tools.py
  devito/operations/interpolators.py
  devito/types/basic.py
  devito/types/dimension.py
  devito/types/equation.py
  devito/types/lazy.py
  devito/types/tensor.py
  tests/test_derivatives.py
Labels: compiler

#1936 ci: Hotfix actions-gh-pages
  .github/workflows/asv.yml
  .github/workflows/documentation.yml
Labels: CI

#1937 ci: Hotfix for actions-gh-pages
  .github/workflows/asv.yml
  .github/workflows/documentation.yml
Labels: CI

#1918 gpu: Update to HPC 22.3, reduced image size
  docker/Dockerfile.nvidia
Labels: installation
