Repository devitocodes/devito, pull requests merged in 2023-11, with the labels that each got.

#2215 arch: Intel PVC mapping
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/parpragma.py
  devito/tools/data_structures.py
  docker/Dockerfile.amd
  docker/Dockerfile.cpu
  docker/Dockerfile.devito
  docker/Dockerfile.nvidia
  tests/test_gpu_openacc.py
Labels: arch

#2256 misc: fix UnboundTuple for None partile
  devito/arch/compiler.py
  devito/core/operator.py
  devito/passes/clusters/blocking.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/parpragma.py
  devito/tools/data_structures.py
  docker/Dockerfile.nvidia
  tests/test_tools.py
  tests/test_unexpansion.py
Labels: bug-py-minor

#2255 compiler: add extra platforms and language to the custom compiler
  devito/arch/compiler.py
  devito/mpi/distributed.py
  devito/types/dense.py
  tests/test_mpi.py
Labels: arch

#2259 api: Always make subsampling factor symbolic
  devito/symbolics/extended_sympy.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/grid.py
  tests/test_dimension.py
Labels: API

#2261 arch: support rocm for gpu info
  .github/workflows/pytest-core-nompi.yml
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/mpi/distributed.py
  tests/test_gpu_common.py
Labels: arch

#2258 api: Add shift and fd order option to all FD operators:
  .github/workflows/tutorials.yml
  devito/finite_differences/differentiable.py
  devito/finite_differences/operators.py
  devito/types/tensor.py
  tests/test_derivatives.py
  tests/test_tensors.py
Labels: API

#2265 mpi: Add utility to get number of ranks on a single node
  devito/mpi/distributed.py
  examples/seismic/preset_models.py
  tests/test_mpi.py
Labels: MPI

#2266 misc: Process args for subdimensions
  devito/core/autotuning.py
  devito/ir/support/space.py
  devito/types/dense.py
  devito/types/dimension.py
Labels: API

#2270 deps: support python 3.12
  .github/workflows/pytest-core-nompi.yml
  devito/__init__.py
  devito/_version.py
  versioneer.py
Labels: dependencies

#2271 compiler: Add missing numpy dtypes
  devito/symbolics/extended_sympy.py
Labels: compiler
