Repository devitocodes/devito, pull requests merged in 2023-05, with the labels that each got.

#2109 mpi: Packed gathers and scatters
  devito/ir/iet/algorithms.py
  devito/ir/iet/nodes.py
  devito/ir/support/basic.py
  devito/mpi/halo_scheme.py
  devito/mpi/routines.py
  devito/passes/clusters/blocking.py
  devito/passes/iet/mpi.py
  devito/tools/dtypes_lowering.py
  devito/types/array.py
  docker/Dockerfile.cpu
  examples/mpi/overview.ipynb
  tests/test_mpi.py
  tests/test_symbolics.py
Labels: MPI

#2117 compiler: Fix OpenMP reductions in tandem with linearize=True
  devito/core/autotuning.py
  devito/ir/iet/nodes.py
  devito/ir/support/__init__.py
  devito/ir/support/properties.py
  devito/ir/support/syncs.py
  devito/ir/support/utils.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/languages/utils.py
  devito/passes/iet/linearization.py
  devito/passes/iet/parpragma.py
  tests/test_linearize.py
Labels: bug-C

#2095 compiler: Change tile use in DeviceAcczier to allow multiple tile sizes
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/parpragma.py
  tests/test_gpu_openacc.py
Labels: GPU, compiler

#2107 compiler: Introduce gpu-create parameter for buffers initialised on device
  devito/core/cpu.py
  devito/core/gpu.py
  devito/operator/operator.py
  devito/passes/__init__.py
  devito/passes/iet/definitions.py
  tests/test_gpu_common.py
Labels: compiler

#2047 reqs: Fix for matplotlib >=3.6.3
  examples/cfd/tools.py
Labels: dependencies

#2096 reqs: Move pyrevolve to optionals and introduce testing-only reqs
  .github/workflows/examples-mpi.yml
  .github/workflows/examples.yml
  .github/workflows/pytest-aws.yaml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/tutorials.yml
  devito/__init__.py
  devito/checkpointing/__init__.py
  docker/Dockerfile.devito
  docs/source/download.rst
  examples/seismic/acoustic/wavesolver.py
  examples/seismic/tti/wavesolver.py
  examples/seismic/viscoacoustic/wavesolver.py
  requirements-optional.txt
  requirements-testing.txt
  requirements.txt
  setup.py
  tests/conftest.py
  tests/test_checkpointing.py
  tests/test_gradient.py
Labels: dependencies

#2119 ci: switch to concurrency settings rather than extra action
  .github/workflows/cancel.yml
  .github/workflows/examples-mpi.yml
  .github/workflows/examples.yml
  .github/workflows/flake8.yml
  .github/workflows/pytest-aws.yaml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  .github/workflows/tutorials.yml
Labels: CI

#2123 deps: sympy 1.12 compat
  devito/core/autotuning.py
  devito/finite_differences/differentiable.py
  requirements.txt
Labels: dependencies

#2125 compiler: Add utility function to normalize sympy arguments
  devito/core/autotuning.py
  devito/symbolics/manipulation.py
Labels: API

#2126 compiler: Patch pickling of GuardFactor and reconstruction
  devito/ir/support/guards.py
  devito/operator/operator.py
  devito/passes/clusters/__init__.py
  devito/passes/clusters/unevaluate.py
  devito/symbolics/unevaluation.py
  tests/test_dse.py
  tests/test_operator.py
  tests/test_pickle.py
Labels: bug-py-minor, compiler

#2136 compiler: Misc compiler tweaks and improvements
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/ir/clusters/cluster.py
  devito/ir/iet/nodes.py
  devito/ir/stree/algorithms.py
  devito/ir/support/properties.py
  devito/ir/support/utils.py
  devito/mpi/halo_scheme.py
  devito/operator/profiling.py
  devito/passes/clusters/asynchrony.py
  devito/passes/clusters/buffering.py
  devito/passes/iet/asynchrony.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/passes/iet/linearization.py
  devito/passes/iet/mpi.py
  devito/passes/iet/parpragma.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/manipulation.py
  tests/test_gpu_common.py
  tests/test_iet.py
  tests/test_linearize.py
  tests/test_mpi.py
  tests/test_symbolics.py
Labels: compiler
