Repository devitocodes/devito, pull requests merged in 2023-08, with the labels that each got.

#2171 docker: add some tweaks to nvidia docker
  .github/workflows/docker-bases.yml
  .github/workflows/docker-devito.yml
  .github/workflows/pytest-gpu.yml
  devito/finite_differences/derivative.py
  devito/ir/iet/nodes.py
  devito/ir/support/space.py
  devito/passes/clusters/aliases.py
  devito/symbolics/inspection.py
  devito/types/dimension.py
  docker/Dockerfile.cpu
  docker/Dockerfile.devito
  docker/Dockerfile.nvidia
  docker/README.md
  requirements-nvidia.txt
  tests/test_builtins.py
  tests/test_derivatives.py
  tests/test_dimension.py
Labels: CI, installation

#2177 CI: pytest setup fix
  docker/Dockerfile.nvidia
  examples/seismic/elastic/elastic_example.py
  examples/seismic/viscoelastic/viscoelastic_example.py
  pytest.ini
  setup.cfg
  tests/test_mpi.py
Labels: CI

#2180 docker: add intel advisor to icx image
  docker/Dockerfile.cpu
  docker/Dockerfile.nvidia
  docker/entrypoint.sh
Labels: installation

#2179 api: prevent factorization for symbolic coefficients
  devito/passes/equations/linearity.py
  tests/test_symbolic_coefficients.py
Labels: bug-py-minor

#2175 misc: Add deviceid to configuration and enhance switchconfig
  devito/__init__.py
  devito/arch/compiler.py
  devito/logger.py
  devito/operator/operator.py
  devito/parameters.py
  devito/types/parallel.py
Labels: arch

#2182 dsl: prevent aggregation for symbolic coefficients
  .github/workflows/examples-mpi.yml
  devito/parameters.py
  devito/passes/equations/linearity.py
  tests/test_symbolic_coefficients.py
Labels: bug-py-minor

#2174 arch: Correct `march` to `mcpu` for ppc
  devito/arch/compiler.py
Labels: arch

#2184 compiler: Enable AVX512 compiler support when available.
  devito/arch/archinfo.py
  devito/arch/compiler.py
Labels: arch

#2185 api: fix symbolic coeffs for cross derivatives
  devito/finite_differences/coefficients.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/tools.py
  examples/seismic/tutorials/07_DRP_schemes.ipynb
  tests/test_symbolic_coefficients.py
Labels: API

#2186 misc: fix openmp= deprecation
  tests/test_autotuner.py
  tests/test_builtins.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_operator.py
  tests/test_pickle.py
Labels: testing

#2190 dsl: No more dynamic classes for AbstractFunctions
  devito/__init__.py
  devito/arch/compiler.py
  devito/builtins/arithmetic.py
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/mpatches/__init__.py
  devito/mpatches/rationaltools.py
  devito/operations/solve.py
  devito/symbolics/printer.py
  devito/symbolics/queries.py
  devito/symbolics/search.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/sparse.py
  devito/types/utils.py
  examples/seismic/source.py
  examples/seismic/tutorials/07_DRP_schemes.ipynb
  tests/test_caching.py
  tests/test_derivatives.py
  tests/test_gpu_common.py
  tests/test_symbolics.py
Labels: bug-py, API
