Repository devitocodes/devito, pull requests merged in 2023-09, with the labels that each got.

#2128 api: Revamp interpolation/injection
  .github/workflows/examples-mpi.yml
  .github/workflows/examples.yml
  devito/ir/equations/algorithms.py
  devito/ir/support/basic.py
  devito/ir/support/utils.py
  devito/operations/interpolators.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/parpragma.py
  devito/symbolics/inspection.py
  devito/symbolics/printer.py
  devito/tools/algorithms.py
  devito/tools/data_structures.py
  devito/tools/dtypes_lowering.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/grid.py
  devito/types/sparse.py
  examples/seismic/elastic/operators.py
  examples/seismic/tutorials/08_snapshotting.ipynb
  requirements-optional.txt
  requirements-testing.txt
  tests/test_buffering.py
  tests/test_builtins.py
  tests/test_caching.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_gpu_common.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_gradient.py
  tests/test_interpolation.py
  tests/test_ir.py
  tests/test_mpi.py
  tests/test_msparse.py
  tests/test_operator.py
  tests/test_pickle.py
Labels: compiler, API

#2198 api: Cleanup and improve SubFunction
  devito/passes/clusters/factorization.py
  devito/symbolics/queries.py
  devito/types/dense.py
  devito/types/sparse.py
  examples/seismic/inversion/inversion_utils.py
  tests/test_dse.py
  tests/test_interpolation.py
  tests/test_pickle.py
  tests/test_sparse.py
Labels: compiler, API

#2205 misc: various Dimension internal fixes
  devito/builtins/initializers.py
  devito/core/autotuning.py
  devito/ir/stree/algorithms.py
  devito/mpi/halo_scheme.py
  devito/operations/interpolators.py
  devito/operator/operator.py
  devito/passes/iet/langbase.py
  devito/passes/iet/parpragma.py
  devito/tools/data_structures.py
  devito/tools/utils.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_interpolation.py
  tests/test_mpi.py
  tests/test_operator.py
Labels: bug-py-minor, API

#2213 compiler: fix arg processing for empty arg update
  devito/tools/data_structures.py
  tests/test_dimension.py
Labels: bug-py-minor

#2216 compiler: prevent radius dependent temps for sparse operations
  devito/ir/clusters/algorithms.py
  tests/test_dse.py
Labels: bug-py-minor, compiler

#2218 compiler: prevent temporary for local reductions
  devito/builtins/utils.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/cluster.py
  devito/ir/equations/equation.py
  devito/ir/support/properties.py
  devito/types/sparse.py
  tests/test_dle.py
  tests/test_dse.py
Labels: bug-py-minor

#2219 api: cleanup SubDimension and SubDomain
  devito/passes/clusters/implicit.py
  devito/types/grid.py
  tests/test_subdomains.py
Labels: API

#2220 compiler: Fix reduction over sparse only
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  devito/ir/clusters/visitors.py
  tests/test_buffering.py
  tests/test_dle.py
Labels: bug-py-minor

#2212 compiler: Fix issue 2194
  devito/ir/support/basic.py
  tests/test_operator.py
Labels: compiler
