Repository devitocodes/devito, pull requests merged in 2023-03, with the labels that each got.

#2072 symbolics: evaluate transpose on elements of tensors in case of deriv…
  devito/types/basic.py
  examples/seismic/elastic/operators.py
  examples/seismic/tutorials/06_elastic.ipynb
  examples/seismic/tutorials/06_elastic_varying_parameters.ipynb
  examples/seismic/tutorials/09_viscoelastic.ipynb
  examples/seismic/viscoelastic/operators.py
  tests/test_tensors.py
Labels: bug-py-minor

#2076 compiler: Fix and improve MIN/MAX codegen
  devito/finite_differences/elementary.py
  devito/ir/iet/visitors.py
  devito/mpi/routines.py
  devito/operator/operator.py
  devito/passes/iet/misc.py
  devito/passes/iet/mpi.py
  devito/symbolics/inspection.py
  devito/symbolics/printer.py
  examples/performance/00_overview.ipynb
  tests/test_linearize.py
  tests/test_symbolics.py
Labels: bug-py

#2080 arch: Support aws graviton
  .github/workflows/cancel.yml
  .github/workflows/pytest-aws.yaml
  devito/arch/archinfo.py
  devito/arch/compiler.py
Labels: CI, arch

#2079 tests: Fix warnings
  .github/workflows/pytest-aws.yaml
  .github/workflows/pytest-core-nompi.yml
  devito/finite_differences/differentiable.py
  devito/types/basic.py
  devito/types/dimension.py
  docker/Dockerfile.nvidia
  docker/Singularity.nvidia.def
  examples/mpi/overview.ipynb
  pytest.ini
  requirements.txt
  tests/test_gradient.py
Labels: testing, CI

#2084 docker: Updating AMD dockerfile to use Ubuntu 22.04.
  docker/Dockerfile.amd
Labels: installation

#2085 ci: make aws ci parallel
  .github/workflows/asv.yml
  .github/workflows/pytest-aws.yaml
Labels: CI

#2087 compiler: only use offloading flags for amd gpu not cpu
  devito/arch/compiler.py
Labels: arch

#1952 Examples: tweaked userapi free surface notebook to use MPI-safe implementation
  examples/userapi/04_boundary_conditions.ipynb
Labels: examples

#2093 compiler: Patch local-SubDim heuristic for blocking
  devito/passes/clusters/blocking.py
  tests/test_dimension.py
Labels: bug-performance-C

#2094 compiler: Do block with partial data reuse
  devito/passes/clusters/blocking.py
  tests/test_dimension.py
Labels: compiler
