Repository devitocodes/devito, pull requests merged in 2023-02, with the labels that each got.

#2058 compiler: Switch from aomp to clang for amd
  .github/workflows/pytest-gpu.yml
  .github/workflows/tutorials.yml
  devito/arch/compiler.py
  docker/Dockerfile.amd
  docker/Dockerfile.cpu
  docker/Dockerfile.nvidia
  tests/test_gpu_openmp.py
Labels: compiler, installation

#2060 compiler: Implement graceful lowering of derivatives (aka "unexpansion")
  .github/workflows/pytest-core-nompi.yml
  devito/arch/compiler.py
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/ir/clusters/cluster.py
  devito/ir/clusters/visitors.py
  devito/ir/equations/algorithms.py
  devito/ir/equations/equation.py
  devito/ir/iet/nodes.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/ir/support/basic.py
  devito/ir/support/guards.py
  devito/ir/support/properties.py
  devito/ir/support/space.py
  devito/ir/support/utils.py
  devito/operator/operator.py
  devito/operator/profiling.py
  devito/passes/clusters/__init__.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/blocking.py
  devito/passes/clusters/cse.py
  devito/passes/clusters/derivatives.py
  devito/passes/clusters/misc.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/passes/iet/languages/C.py
  devito/passes/iet/languages/openacc.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/inspection.py
  devito/symbolics/manipulation.py
  devito/symbolics/queries.py
  devito/tools/data_structures.py
  devito/tools/dtypes_lowering.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dimension.py
  devito/types/grid.py
  devito/types/misc.py
  examples/mpi/overview.ipynb
  examples/performance/00_overview.ipynb
  examples/userapi/05_conditional_dimension.ipynb
  tests/test_cinterface.py
  tests/test_derivatives.py
  tests/test_dimension.py
  tests/test_dse.py
  tests/test_ir.py
  tests/test_linearize.py
  tests/test_lower_exprs.py
  tests/test_operator.py
  tests/test_subdomains.py
  tests/test_symbolics.py
Labels: compiler

#2065 compiler: Patch data dependencies across Jumps
  devito/ir/support/basic.py
Labels: compiler

#2052 symbolics: use devito floor instead of Undefined Function
  devito/finite_differences/elementary.py
  devito/mpi/routines.py
  devito/passes/iet/misc.py
  devito/passes/iet/mpi.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/manipulation.py
  devito/symbolics/printer.py
  devito/types/sparse.py
  examples/performance/00_overview.ipynb
  requirements.txt
  tests/test_linearize.py
  tests/test_pickle.py
  tests/test_skewing.py
  tests/test_symbolics.py
Labels: API

#2069 compiler: Relax _mark_overlappable
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/tutorials.yml
  README.md
  devito/ir/support/basic.py
  devito/passes/iet/mpi.py
Labels: compiler

#2070 compiler: Handle IndexedBase DDA across Jumps/Barriers
  devito/ir/support/basic.py
  tests/test_ir.py
Labels: bug-py-minor
