Repository devitocodes/devito, pull requests merged in 2023-07, with the labels that each got.

#2150 compiler: Add guards to prevent OOB when streaming buffers with ConditionalDimension
  devito/passes/clusters/buffering.py
  tests/test_buffering.py
  tests/test_gpu_common.py
Labels: bug-py-minor

#2160 compiler: prevent adding breaking guard to nokey
  devito/ir/support/guards.py
  devito/passes/clusters/buffering.py
Labels: bug-py-minor

#2162 docker: revamp base deployment
  .github/workflows/docker-bases.yml
  .github/workflows/docker-devito.yml
  .github/workflows/examples.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  .github/workflows/tutorials.yml
  conftest.py
  devito/arch/compiler.py
  devito/core/autotuning.py
  devito/types/dense.py
  devito/types/dimension.py
  docker/Dockerfile.amd
  docker/Dockerfile.cpu
  docker/Dockerfile.devito
  docker/Dockerfile.nvidia
  docker/README.md
  examples/cfd/08_shallow_water_equation.ipynb
  examples/seismic/source.py
  requirements-optional.txt
  requirements-testing.txt
  requirements.txt
Labels: dependencies, CI, installation

#2158 ci: Add python 3.11 and minor CI fixing
  .github/workflows/examples.yml
  .github/workflows/flake8.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/tutorials.yml
  devito/tools/utils.py
  versioneer.py
Labels: CI

#2166 CI: fix asv devito install
  .github/workflows/asv.yml
Labels: CI

#2167 CI: fix asv setup
  .github/workflows/asv.yml
  benchmarks/regression/asv.conf.json
  setup.py
Labels: CI

#2165 compiler: fix non arithmetic distances
  devito/passes/clusters/aliases.py
  tests/test_dse.py
Labels: bug-py-minor

#2164 compiler: Keep -qopenmp by default after icx 2023.2
  devito/arch/compiler.py
  tests/test_mpi.py
Labels: compiler

#2168 api: Allow parametric par-tile as input
  devito/core/operator.py
Labels: API

#2169 compiler: prevent Eq dims to be lost if only implicit
  devito/ir/clusters/cluster.py
  tests/test_dse.py
Labels: bug-py-minor

#2172 docker: switch to intelpython for icc/icx build
  .github/workflows/pytest-core-nompi.yml
  docker/Dockerfile.cpu
  tests/test_environment.py
Labels: installation
