Repository devitocodes/devito, pull requests merged in 2023-06, with the labels that each got.

#2112 compiler: Improve lowering of IndexDerivatives
  devito/ir/clusters/algorithms.py
  devito/ir/support/basic.py
  devito/operator/operator.py
  devito/passes/clusters/derivatives.py
  devito/passes/clusters/misc.py
  devito/passes/iet/linearization.py
  devito/passes/iet/misc.py
  devito/tools/abc.py
  devito/types/dimension.py
  devito/types/misc.py
  tests/conftest.py
  tests/test_dse.py
  tests/test_symbolics.py
  tests/test_unexpansion.py
Labels: compiler

#2139 compiler: Pass operator arguments to downstream operators
  devito/operator/operator.py
Labels: compiler

#2051 arch: Add ICX support
  .github/workflows/docker-bases.yml
  .github/workflows/pytest-core-nompi.yml
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/parameters.py
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_buffering.py
  tests/test_dimension.py
Labels: arch

#2138 compiler: Misc compiler fixes and improvements -- part II
  devito/arch/compiler.py
  devito/ir/clusters/algorithms.py
  devito/ir/iet/algorithms.py
  devito/ir/iet/visitors.py
  devito/ir/stree/algorithms.py
  devito/mpi/halo_scheme.py
  devito/mpi/routines.py
  devito/operator/operator.py
  devito/passes/__init__.py
  devito/passes/clusters/buffering.py
  devito/passes/iet/mpi.py
  devito/passes/iet/parpragma.py
  devito/tools/abc.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/misc.py
  devito/types/utils.py
  examples/mpi/overview.ipynb
  tests/test_gpu_common.py
  tests/test_mpi.py
  tests/test_pickle.py
  tests/test_symbolics.py
Labels: compiler

#2141 compiler: Revert "compiler: Relax WaitLock regions in a ScheduleTree"
  devito/ir/stree/algorithms.py
  devito/mpi/routines.py
  tests/test_gpu_common.py
Labels: bug-C

#2148 compiler: Fix pickling of aliasing SparseFunction
  devito/types/sparse.py
  tests/test_pickle.py
Labels: bug-py-minor

#2154 compiler: Fix CondDim's factor auto-override
  devito/operator/operator.py
  devito/types/dense.py
  devito/types/dimension.py
  tests/test_dimension.py
Labels: bug-py

#2143 mpi: Instrument compute0 core after specialising as ComputeCall
  devito/ir/iet/efunc.py
  devito/mpi/routines.py
  devito/operator/profiling.py
  devito/passes/iet/instrument.py
  tests/test_mpi.py
Labels: MPI

#2142 compiler: Add opkwargs property to ArgumentsMap
  devito/operator/operator.py
Labels: compiler
