Repository devitocodes/devito, pull requests merged in 2023-01, with the labels that each got.

#2046 CI: switch macos runner to latest gcc version
  .github/workflows/tutorials.yml
Labels: CI

#2042 compiler: Extensions for parlang backends
  .github/workflows/docker-devito.yml
  .github/workflows/pytest-gpu.yml
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/builtins/initializers.py
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/ir/clusters/cluster.py
  devito/ir/iet/nodes.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/ir/stree/algorithms.py
  devito/ir/support/basic.py
  devito/ir/support/guards.py
  devito/ir/support/properties.py
  devito/ir/support/utils.py
  devito/mpi/routines.py
  devito/operator/operator.py
  devito/operator/registry.py
  devito/passes/clusters/buffering.py
  devito/passes/clusters/misc.py
  devito/passes/iet/definitions.py
  devito/passes/iet/langbase.py
  devito/passes/iet/linearization.py
  devito/passes/iet/misc.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/manipulation.py
  devito/symbolics/printer.py
  devito/symbolics/queries.py
  devito/tools/__init__.py
  devito/tools/dtypes_lowering.py
  devito/tools/utils.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dimension.py
  devito/types/object.py
  docker/Dockerfile.amd
  examples/seismic/model.py
  tests/test_buffering.py
  tests/test_builtins.py
  tests/test_dimension.py
  tests/test_gpu_common.py
  tests/test_iet.py
  tests/test_linearize.py
  tests/test_operator.py
  tests/test_symbolics.py
Labels: compiler

#2055 docker: add AMD HIP build to base docker
  .github/workflows/docker-bases.yml
Labels: CI, installation

#2057 docker: Switch to rocm 4.5.2
  docker/Dockerfile.amd
Labels: installation
