Repository devitocodes/devito, pull requests merged in 2023-10, with the labels that each got.

#2221 documentation: update ci for new website setup
  .github/workflows/documentation.yml
  FAQ.md
  docs/Makefile
  docs/make.bat
  docs/source/_static/devito_logo.png
  docs/source/_static/devito_style.css
  docs/source/_templates/layout.html
  docs/source/builtins.rst
  docs/source/conf.py
  docs/source/constant.rst
  docs/source/dimension.rst
  docs/source/download.rst
  docs/source/equation.rst
  docs/source/finite-difference.rst
  docs/source/function.rst
  docs/source/grid.rst
  docs/source/grids.rst
  docs/source/index.rst
  docs/source/operator.rst
  docs/source/precsparsefunction.rst
  docs/source/precsparsetimefunction.rst
  docs/source/sparsefunction.rst
  docs/source/sparsetimefunction.rst
  docs/source/subdomain.rst
  docs/source/symbolic.rst
  docs/source/tensorfunction.rst
  docs/source/tensortimefunction.rst
  docs/source/timefunction.rst
  docs/source/userapi.rst
  docs/source/vectorfunction.rst
  docs/source/vectortimefunction.rst
Labels: documentation

#2225 compiler: Rework multi-level buffering
  devito/ir/support/syncs.py
  devito/passes/clusters/asynchrony.py
  devito/passes/clusters/buffering.py
  devito/passes/clusters/misc.py
  devito/passes/clusters/utils.py
  devito/types/dimension.py
  tests/test_dle.py
Labels: compiler

#2227 ci: add intel missing gpu drivers
  docker/Dockerfile.cpu
  requirements-mpi.txt
Labels: dependencies, CI

#2228 deps: fix intel drivers
  docker/Dockerfile.cpu
Labels: dependencies

#2226 compiler: prevent reduction clause for perfect-enough outer loops
  devito/passes/iet/langbase.py
  devito/passes/iet/parpragma.py
  tests/test_adjoint.py
  tests/test_dle.py
  tests/test_gpu_common.py
Labels: compiler

#2195 Update FAQ.md
  FAQ.md
Labels: documentation

#2232 compiler: Patch cluster.is_sparse
  devito/ir/clusters/cluster.py
  tests/test_lower_clusters.py
Labels: bug-C

#2230 compiler: prevent multisubdimension expressions duplicates
  devito/passes/clusters/implicit.py
Labels: compiler

#2234 api: enforce interpolation radius to be smaller than any input space …
  devito/operations/interpolators.py
  devito/types/sparse.py
  tests/test_dle.py
  tests/test_gpu_common.py
  tests/test_interpolation.py
  tests/test_mpi.py
  tests/test_operator.py
Labels: API

#2208 compiler: Revamp lowering of IndexDerivatives
  conftest.py
  devito/core/operator.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/finite_differences/tools.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/cluster.py
  devito/ir/clusters/visitors.py
  devito/ir/equations/algorithms.py
  devito/ir/equations/equation.py
  devito/ir/iet/nodes.py
  devito/ir/stree/algorithms.py
  devito/ir/support/__init__.py
  devito/ir/support/basic.py
  devito/ir/support/guards.py
  devito/ir/support/properties.py
  devito/ir/support/space.py
  devito/ir/support/utils.py
  devito/operator/operator.py
  devito/operator/profiling.py
  devito/passes/clusters/__init__.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/blocking.py
  devito/passes/clusters/buffering.py
  devito/passes/clusters/cse.py
  devito/passes/clusters/derivatives.py
  devito/passes/clusters/factorization.py
  devito/passes/clusters/implicit.py
  devito/passes/clusters/misc.py
  devito/passes/equations/linearity.py
  devito/passes/iet/engine.py
  devito/passes/iet/instrument.py
  devito/passes/iet/misc.py
  devito/symbolics/inspection.py
  devito/symbolics/printer.py
  devito/symbolics/search.py
  devito/tools/data_structures.py
  devito/tools/dtypes_lowering.py
  devito/tools/utils.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/misc.py
  devito/types/object.py
  devito/types/parallel.py
  devito/types/tensor.py
  examples/performance/01_gpu.ipynb
  tests/test_caching.py
  tests/test_derivatives.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_gpu_common.py
  tests/test_linearize.py
  tests/test_mpi.py
  tests/test_pickle.py
  tests/test_symbolics.py
  tests/test_unexpansion.py
Labels: compiler

#2243 compiler: Patch custom coefficients
  devito/passes/iet/definitions.py
  devito/symbolics/extended_sympy.py
  tests/test_unexpansion.py
Labels: bug-py-minor

#2244 compiler: Introduce symbolic fencing
  devito/ir/clusters/cluster.py
  devito/ir/clusters/visitors.py
  devito/ir/stree/algorithms.py
  devito/ir/support/basic.py
  devito/passes/clusters/asynchrony.py
  devito/passes/clusters/misc.py
  devito/passes/clusters/utils.py
  devito/types/misc.py
  devito/types/parallel.py
  tests/test_ir.py
Labels: compiler

#2248 compiler: Patch symbolic coefficients over cross derivatives
  devito/finite_differences/coefficients.py
  devito/finite_differences/differentiable.py
  devito/types/dense.py
  tests/test_symbolic_coefficients.py
  tests/test_unexpansion.py
Labels: bug-py

#2246 dsl: Patch domain decomposition bug with SubDomains
  devito/data/decomposition.py
  devito/mpi/distributed.py
  devito/types/grid.py
  tests/test_subdomains.py
Labels: bug-py-minor, MPI

#2250 compiler: Patch compare_ops for IndexDerivatives
  devito/symbolics/inspection.py
  tests/test_unexpansion.py
Labels: bug-py

#2251 compiler: Hotfix compare-ops
  devito/symbolics/inspection.py
  tests/test_unexpansion.py
Labels: bug-C

#2253 compiler: Machinery to generate vector types
  devito/mpi/routines.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/types/array.py
Labels: compiler

#2254 api: prevent derivative shortcut with incompatible fd order
  devito/finite_differences/differentiable.py
  devito/ir/clusters/cluster.py
  tests/test_derivatives.py
  tests/test_lower_exprs.py
Labels: API
