Repository devitocodes/devito, pull requests merged in 2024-12, with the labels that each got.

#2494 misc: Fixup Profiler.add_global_vanilla
  devito/operator/profiling.py
Labels: benchmarking

#2495 misc: Fix operator output with OI=None
  devito/operator/operator.py
Labels: misc

#2496 misc: Fix operator output with gflopss=None
  devito/operator/operator.py
Labels: misc

#2497 api: fix alias for buffering
  devito/types/basic.py
Labels: bug-py

#2499 docs: Update CITATION.md
  CITATION.md
Labels: documentation

#2477 compiler: Rework HaloSpot optimization
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/ir/support/basic.py
  devito/mpi/halo_scheme.py
  devito/passes/iet/mpi.py
  examples/mpi/overview.ipynb
  examples/seismic/abc_methods/03_pml.ipynb
  examples/seismic/tutorials/09_viscoelastic.ipynb
  examples/seismic/viscoacoustic/operators.py
  examples/seismic/viscoelastic/operators.py
  tests/test_dse.py
  tests/test_mpi.py
Labels: MPI, compiler

#2501 compiler: Generate fminf/fmaxf where necessary
  devito/symbolics/printer.py
  tests/test_symbolics.py
Labels: bug-C-minor

#2503 compiler: Avoid allocating Bundles on the host if transient
  devito/passes/iet/definitions.py
Labels: bug-performance-C

#2506 misc: Prevent builtins on transient functions
  devito/builtins/arithmetic.py
  devito/builtins/initializers.py
  devito/builtins/utils.py
  tests/test_gpu_common.py
Labels: bug-C-minor

#2502 compiler: Add 'groupby' mode to MapNodes visitor
  devito/ir/iet/visitors.py
  tests/test_visitors.py
Labels: misc

#2507 compiler: Default CustomDimension.local to True
  devito/types/dimension.py
  tests/test_mpi.py
Labels: bug-performance-C
