Repository devitocodes/devito, pull requests merged in 2024-09, with the labels that each got.

#2446 compiler: Add various performance optimization variants
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/finite_differences/differentiable.py
  devito/ir/clusters/visitors.py
  devito/ir/support/utils.py
  devito/passes/clusters/cse.py
  devito/passes/clusters/factorization.py
  devito/passes/clusters/utils.py
  devito/symbolics/manipulation.py
  devito/types/parallel.py
  examples/performance/00_overview.ipynb
  examples/performance/01_gpu.ipynb
  tests/test_cse.py
  tests/test_dse.py
  tests/test_linearize.py
  tests/test_roundoff.py
  tests/test_unexpansion.py
Labels: compiler

#2449 compiler: Patch mapify-reduce for SparseTimeFunctions
  devito/ir/clusters/algorithms.py
  devito/ir/equations/equation.py
Labels: bug-C

#2452 compiler: Hotfix and simplify minimize_symbols
  devito/ir/iet/visitors.py
  devito/passes/iet/misc.py
Labels: bug-performance-C

#2450 examples: Fix ADER notebook numbering
  examples/seismic/tutorials/16_ader_fd.ipynb
Labels: examples

#2458 API: revamp cross derivative shortcuts
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/finite_differences/tools.py
  devito/ir/equations/algorithms.py
  devito/symbolics/manipulation.py
  devito/symbolics/search.py
  devito/types/equation.py
  tests/test_derivatives.py
  tests/test_symbolic_coefficients.py
  tests/test_tensors.py
Labels: bug-py, API

#2453 compiler: Minor tweaks for elastic code gen
  devito/arch/compiler.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/tools.py
  devito/ir/clusters/cluster.py
  devito/passes/clusters/misc.py
  devito/symbolics/manipulation.py
  devito/types/basic.py
  devito/types/dimension.py
  tests/test_differentiable.py
  tests/test_rebuild.py
Labels: compiler
