Repository devitocodes/devito, pull requests merged in 2024-07, with the labels that each got.

#2394 MPI: Fix data assignement for single mpi rank and factor haloupdate
  devito/data/data.py
  devito/mpi/distributed.py
  devito/passes/iet/mpi.py
  devito/types/sparse.py
  tests/test_data.py
  tests/test_mpi.py
Labels: bug-py, MPI

#2392 compiler: Patch CSE in presence of conditionals
  devito/passes/clusters/cse.py
  tests/test_dse.py
Labels: bug-C

#2396 compiler: Yet another batch of compilation tweaks
  devito/__init__.py
  devito/core/gpu.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/cluster.py
  devito/ir/iet/nodes.py
  devito/ir/iet/utils.py
  devito/ir/iet/visitors.py
  devito/ir/support/basic.py
  devito/operator/operator.py
  devito/passes/__init__.py
  devito/passes/clusters/blocking.py
  devito/passes/clusters/misc.py
  devito/passes/iet/engine.py
  devito/passes/iet/languages/openacc.py
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/languages/utils.py
  devito/passes/iet/linearization.py
  devito/passes/iet/parpragma.py
  devito/symbolics/manipulation.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dimension.py
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_gpu_openacc.py
  tests/test_gpu_openmp.py
  tests/test_linearize.py
  tests/test_mpi.py
Labels: compiler

#2399 compiler: Default to index-mode=int32
  devito/core/operator.py
  devito/types/dense.py
  examples/performance/01_gpu.ipynb
  tests/test_linearize.py
Labels: compiler

#2402 compiler: Strengthen int32 error check
  devito/types/dense.py
Labels: bug-py-minor

#2393 compiler: Drop SubDomainSet earlier during compilation for more graceful lowering
  devito/passes/clusters/implicit.py
  devito/types/dimension.py
  devito/types/grid.py
  tests/test_subdomains.py
Labels: compiler, API

#2406 misc: minor miscelanous fixes
  devito/types/basic.py
  devito/types/dense.py
  devito/types/tensor.py
  tests/test_tensors.py
Labels: bug-py-minor, MPI, API

#2408 compiler: Patch bug in SubDomainSet lowering
  devito/passes/clusters/implicit.py
  tests/test_subdomains.py
Labels: compiler

#2410 compiler: fix cse with different conditionals
  devito/ir/support/utils.py
  devito/passes/clusters/cse.py
  devito/types/equation.py
  tests/test_dse.py
Labels: bug-py, compiler

#2411 compiler: Revamp MultiSubDimension lowering
  devito/ir/equations/algorithms.py
  devito/operator/operator.py
  devito/passes/clusters/implicit.py
  devito/types/dimension.py
  devito/types/grid.py
Labels: compiler

#2413 api: Support combination of condition and factor for ConditionalDimension
  devito/ir/equations/equation.py
  devito/types/dimension.py
  devito/types/relational.py
  tests/test_dimension.py
Labels: API

#2414 api: Patch ConditioanlDImension args
  devito/types/dimension.py
Labels: bug-py-minor

#2412 compiler: Bump default block size
  devito/types/dimension.py
  tests/test_dse.py
Labels: compiler

#2415 arch: Support more platforms
  devito/__init__.py
  devito/arch/archinfo.py
  devito/arch/compiler.py
  tests/test_arch.py
Labels: arch

#2417 compiler: Fix parlang reductions over >= 4 loops
  devito/arch/archinfo.py
  devito/ir/clusters/algorithms.py
  devito/passes/clusters/blocking.py
  devito/types/dimension.py
  tests/test_gpu_common.py
Labels: bug-py-minor

#2419 arch: fix switchconfig with new setup
  devito/arch/compiler.py
  tests/test_arch.py
Labels: arch

#2425 dsl: Make CondEq and CondNe easier to import
  devito/__init__.py
Labels: misc

#2423 deps: Drop python 3.8
  .github/workflows/examples.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  requirements-optional.txt
  setup.py
  tests/test_buffering.py
  tests/test_gradient.py
  tests/test_roundoff.py
Labels: CI

#2426 compiler: Tweak par-tile unrolling and revamp MPI topology
  FAQ.md
  devito/__init__.py
  devito/core/operator.py
  devito/mpi/distributed.py
  devito/parameters.py
  devito/passes/clusters/blocking.py
  devito/types/grid.py
  tests/test_mpi.py
Labels: compiler

#2429 api: Make Derivative Reconstructable
  devito/finite_differences/derivative.py
  devito/passes/equations/linearity.py
  devito/tools/abc.py
  tests/test_derivatives.py
Labels: bug-py

#2418 misc: Fix EnrichedTuple rebuilding
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/operations/interpolators.py
  devito/tools/data_structures.py
  devito/types/utils.py
  tests/test_pickle.py
  tests/test_staggered_utils.py
Labels: bug-py-minor
