Repository devitocodes/devito, pull requests merged in 2024-01, with the labels that each got.

#2288 compiler: Improve IndexDerivative lowering
  devito/passes/clusters/derivatives.py
  tests/test_unexpansion.py
Labels: compiler

#2291 deps: Update rocm version
  docker/Dockerfile.amd
  setup.py
Labels: dependencies, CI

#2294 example: small cleanup of tti for easier reuse
  devito/arch/archinfo.py
  devito/arch/compiler.py
  devito/builtins/utils.py
  devito/types/dimension.py
  examples/seismic/preset_models.py
  examples/seismic/tti/operators.py
  tests/test_dse.py
Labels: examples, arch

#2295 data: Prevent allocator info to be lost at finalize
  devito/data/data.py
Labels: bug-py-minor

#2297 arch: patch compiler version
  devito/arch/archinfo.py
  devito/arch/compiler.py
  examples/seismic/model.py
Labels: arch

#2296 compiler: Revamp data alignment
  devito/arch/archinfo.py
  devito/core/cpu.py
  devito/data/allocators.py
  devito/data/data.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/analysis.py
  devito/ir/support/properties.py
  devito/logger.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/iet/definitions.py
  devito/passes/iet/engine.py
  devito/passes/iet/linearization.py
  devito/passes/iet/misc.py
  devito/passes/iet/parpragma.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/misc.py
  devito/types/tensor.py
  examples/userapi/01_dsl.ipynb
  tests/test_data.py
  tests/test_dse.py
Labels: compiler

#2300 compiler: Misc codegen enhancements
  devito/arch/archinfo.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/manipulation.py
  devito/symbolics/printer.py
  tests/test_iet.py
Labels: compiler
