Repository devitocodes/devito, pull requests merged in 2024-06, with the labels that each got.

#2380 compiler: Misc compiler improvements
  conftest.py
  devito/__init__.py
  devito/arch/archinfo.py
  devito/builtins/arithmetic.py
  devito/builtins/utils.py
  devito/data/allocators.py
  devito/data/data.py
  devito/mpi/distributed.py
  devito/mpi/routines.py
  devito/operator/operator.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/grid.py
  devito/types/sparse.py
Labels: compiler

#2381 tests: Fixup conftest's set_run_reset()
  conftest.py
Labels: bug-py-minor

#2382 CI: fix decoupler config to use correct python
  conftest.py
Labels: CI

#2384 ci: avoid apt upgrade use base as is (updated every week}
  docker/Dockerfile.devito
Labels: CI

#2385 compiler: Tweaks to enable decoupling on GPUs
  conftest.py
  devito/arch/archinfo.py
  tests/test_pickle.py
Labels: compiler

#2388 API: fix printer dtype processing
  devito/passes/iet/linearization.py
  devito/symbolics/printer.py
  devito/types/sparse.py
  docker/Dockerfile.intel
  tests/test_linearize.py
Labels: bug-py-minor, API

#2391 deps: support numpy 2.0
  .github/workflows/pytest-core-nompi.yml
  devito/__init__.py
  devito/arch/compiler.py
  requirements.txt
  setup.py
  tests/test_interpolation.py
  tests/test_sparse.py
Labels: dependencies, installation

#2390 compiler: Improve data streaming backend
  devito/arch/archinfo.py
  devito/core/operator.py
  devito/ir/clusters/algorithms.py
  devito/ir/stree/algorithms.py
  devito/mpi/halo_scheme.py
  devito/operator/operator.py
  devito/passes/clusters/buffering.py
  devito/passes/iet/instrument.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/parallel.py
  devito/types/utils.py
  tests/test_dle.py
  tests/test_gpu_common.py
Labels: compiler
