Repository devitocodes/devito, pull requests merged in 2024-08, with the labels that each got.

#2435 compiler: fix unevaluation of sparse cluster
  devito/passes/clusters/unevaluate.py
  tests/test_pickle.py
Labels: bug-py

#2432 compiler: Patch indirect ConditionalDimension
  devito/ir/equations/equation.py
  tests/test_dimension.py
Labels: bug-py-minor

#2436 dsl: Fix missing sympy assumptions during rebuilding
  devito/tools/abc.py
  devito/types/basic.py
  tests/test_caching.py
  tests/test_pickle.py
  tests/test_symbolics.py
Labels: bug-py-minor, compiler

#2433 types: Introduce abstract class LocalType
  devito/ir/iet/utils.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/object.py
Labels: API

#2441 compiler: respect fetch direction
  devito/passes/clusters/asynchrony.py
Labels: compiler

#2439 api: make sure staggered FD interpolates shifts
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/finite_differences/tools.py
  tests/test_derivatives.py
  tests/test_differentiable.py
  tests/test_dse.py
  tests/test_mpi.py
Labels: API

#2438 dsl: Improve Function rebuilding and use of preexisting arrays as Function data
  devito/data/allocators.py
  devito/types/basic.py
  devito/types/dense.py
  tests/test_data.py
  tests/test_docstrings.py
  tests/test_rebuild.py
Labels: API
