Repository devitocodes/devito, pull requests merged in 2024-05, with the labels that each got.

#2369 api: Always expand time derivatives
  devito/finite_differences/finite_difference.py
  tests/test_unexpansion.py
Labels: bug-py-minor

#2338 examples: Add an example notebook for ADER-FD schemes
  examples/seismic/tutorials/16_ader_fd.ipynb
Labels: examples

#2372 compiler: sequentialise halo touch
  devito/ir/clusters/algorithms.py
Labels: compiler

#2359 reqs: Update cached_property to functools version
  .github/workflows/pytest-core-nompi.yml
  devito/arch/archinfo.py
  devito/data/decomposition.py
  devito/finite_differences/coefficients.py
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/ir/clusters/cluster.py
  devito/ir/equations/equation.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/support/basic.py
  devito/ir/support/space.py
  devito/mpi/distributed.py
  devito/mpi/halo_scheme.py
  devito/operations/interpolators.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/buffering.py
  devito/passes/iet/parpragma.py
  devito/tools/utils.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/equation.py
  devito/types/grid.py
  devito/types/lazy.py
  devito/types/parallel.py
  devito/types/sparse.py
  devito/types/tensor.py
  examples/seismic/source.py
  requirements.txt
  setup.py
  tests/test_dse.py
  tests/test_mpi.py
  versioneer.py
Labels: dependencies

#2377 dsl: Correct retention of wrong branch in filter_ordered
  devito/tools/utils.py
Labels: bug-py-minor

#2379 mpi: Fix data_gather for sparse functions
  devito/mpi/distributed.py
  tests/test_data.py
Labels: bug-py, MPI, API

#2344 compiler: Support for C-level MPI_Allreduce
  devito/builtins/arithmetic.py
  devito/builtins/utils.py
  devito/core/gpu.py
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/cluster.py
  devito/ir/stree/algorithms.py
  devito/ir/support/basic.py
  devito/ir/support/space.py
  devito/mpi/reduction_scheme.py
  devito/mpi/routines.py
  devito/operator/operator.py
  devito/passes/iet/langbase.py
  devito/passes/iet/mpi.py
  devito/types/sparse.py
  tests/test_builtins.py
  tests/test_error_checking.py
  tests/test_mpi.py
  tests/test_sparse.py
Labels: compiler
