Repository devitocodes/devito, pull requests merged in 2024-02, with the labels that each got.

#2301 compiler: Generate less integer arithmetic
  devito/ir/clusters/cluster.py
  devito/ir/support/utils.py
  devito/passes/clusters/derivatives.py
  tests/test_unexpansion.py
Labels: compiler

#2302 compiler: Fix space conditions with loop blocking
  devito/passes/clusters/blocking.py
  tests/test_dimension.py
Labels: bug-C

#2304 arch: Add denormal flag for clang
  devito/arch/compiler.py
Labels: arch

#2309 compiler: Block reductions irrespective of par-tile
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/passes/clusters/blocking.py
Labels: bug-C

#2312 ci: Update actions for nodejs version deprecation
  .github/workflows/asv.yml
  .github/workflows/docker-bases.yml
  .github/workflows/docker-devito.yml
  .github/workflows/examples-mpi.yml
  .github/workflows/examples.yml
  .github/workflows/flake8.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  .github/workflows/pythonpublish.yml
  .github/workflows/triggers.yml
  .github/workflows/tutorials.yml
Labels: CI

#2308 Correct the Poisson equation in the cavity flow example
  examples/cfd/07_cavity_flow.ipynb
Labels: examples

#2313 misc: Use `str` for generalization
  devito/operator/operator.py
Labels: bug-py-minor

#2311 compiler: Optimize normalize_reductions_dense
  devito/ir/clusters/algorithms.py
Labels: compiler

#2315 compiler: Fix min/max reductions to be backend-portable
  devito/ir/clusters/algorithms.py
  devito/ir/equations/equation.py
  devito/passes/clusters/factorization.py
  devito/passes/iet/misc.py
  devito/passes/iet/parpragma.py
  devito/symbolics/extended_sympy.py
  devito/symbolics/printer.py
  tests/test_dle.py
Labels: bug-C

#2303 mpi: Generate deterministic code for overlap mode
  devito/mpi/halo_scheme.py
Labels: MPI

#2317 compiler: Revamp linearization
  devito/passes/iet/linearization.py
  tests/test_linearize.py
Labels: compiler

#2318 deps: prevent codecov error on local docker
  docker/entrypoint.sh
Labels: dependencies

#2310 compiler: Revamp lowering of IndexDerivatives
  devito/core/cpu.py
  devito/core/gpu.py
  devito/core/operator.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/finite_difference.py
  devito/ir/equations/algorithms.py
  devito/operator/operator.py
  devito/passes/clusters/derivatives.py
  devito/passes/iet/mpi.py
  tests/test_derivatives.py
  tests/test_operator.py
  tests/test_unexpansion.py
Labels: compiler

#2321 compiler: Hotfix unevaluation.Pow(1, ...)
  devito/symbolics/unevaluation.py
Labels: bug-py-minor

#2319 examples: Update MPI notebook to reference inner and outer halo terminology
  examples/mpi/overview.ipynb
Labels: examples

#2322 compiler: Add Weights.value utility
  devito/finite_differences/differentiable.py
Labels: compiler

#2223 misc: Docstring updates
  README.md
  devito/arch/compiler.py
  devito/builtins/arithmetic.py
  devito/finite_differences/derivative.py
  devito/types/constant.py
  devito/types/dense.py
  devito/types/dimension.py
  devito/types/equation.py
  devito/types/grid.py
  devito/types/sparse.py
  devito/types/tensor.py
  examples/userapi/01_dsl.ipynb
  examples/userapi/05_conditional_dimension.ipynb
Labels: documentation
