Repository devitocodes/devito, pull requests merged in 2024-10, with the labels that each got.

#2431 compiler: Remove counters from subdomains and automatically generate unique names
  devito/ir/equations/algorithms.py
  devito/ir/support/symregistry.py
  devito/types/basic.py
  devito/types/dimension.py
  devito/types/grid.py
  examples/cfd/01_convection_revisited.ipynb
  examples/userapi/03_subdomains.ipynb
  tests/test_dimension.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_mpi.py
  tests/test_pickle.py
  tests/test_subdomains.py
Labels: compiler

#2462 compiler: Add missing symbolic casts
  devito/symbolics/extended_sympy.py
  devito/tools/dtypes_lowering.py
Labels: compiler

#2463 deps: fix deprecated pkg_resources
  setup.py
Labels: installation

#2466 arch: add rpath option to include_dirs
  devito/arch/compiler.py
  devito/passes/iet/engine.py
Labels: arch

#2461 arch: Avoid deprecated compiler flags
  devito/arch/compiler.py
Labels: arch

#2468 arch: make sure Device get thread config from host
  .github/workflows/examples.yml
  devito/arch/archinfo.py
  tests/test_gpu_common.py
Labels: arch

#2472 compiler: Fixup minor cire-rotate bug
  devito/passes/clusters/aliases.py
  devito/passes/iet/misc.py
  examples/performance/00_overview.ipynb
  tests/test_dle.py
  tests/test_dse.py
Labels: bug-py-minor

#2473 API: Fix Sparse rebuild with explicit empty subfunctions
  devito/types/sparse.py
  tests/test_rebuild.py
Labels: API

#2476 compiler: Improve CIRE's cost model
  devito/passes/clusters/aliases.py
  tests/test_dse.py
Labels: compiler
