Repository devitocodes/devito, pull requests merged in 2025-08, with the labels that each got.

#2686 Remove dangling layers.
  .github/workflows/docker-devito.yml
  .github/workflows/pytest-gpu.yml
Labels: CI

#2659 compiler: Add a utility to estimate memory usage for an operator
  .github/workflows/pytest-gpu.yml
  FAQ.md
  devito/operator/operator.py
  devito/tools/data_structures.py
  devito/types/dense.py
  devito/types/sparse.py
  examples/userapi/02_apply.ipynb
  tests/test_operator.py
Labels: API

#2698 mpi: Prevent errors with single rank
  .github/workflows/pytest-gpu.yml
  devito/builtins/arithmetic.py
  devito/data/data.py
Labels: MPI

#2702 install: Remove files and directories not needed for install
  MANIFEST.in
  devito/builtins/arithmetic.py
  pyproject.toml
Labels: installation

#2715 arch: prevent shell string escape in codepy cmdline strings
  devito/arch/compiler.py
Labels: arch
