Repository devitocodes/devito, pull requests merged in 2025-02, with the labels that each got.

#2529 CI: Revert amd CI to a stable rocm for openmp offloading
  .github/workflows/docker-bases.yml
  docker/Dockerfile.amd
  docker/Dockerfile.devito
Labels: testing, dependencies

#2530 api: Relax custom coefficient spacing enforcement
  devito/finite_differences/tools.py
  tests/test_symbolic_coefficients.py
Labels: API

#2537 arch: Support Grace arm architecture
  devito/arch/archinfo.py
  devito/arch/compiler.py
Labels: arch

#2538 compiler: Misc extensions towards supporting thread block clustering
  devito/arch/archinfo.py
  devito/ir/iet/efunc.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/ir/support/properties.py
  devito/ir/support/space.py
  devito/operator/operator.py
  devito/passes/clusters/cse.py
  devito/passes/clusters/misc.py
  devito/passes/iet/errors.py
  devito/symbolics/extended_sympy.py
  devito/types/array.py
  devito/types/basic.py
  devito/types/misc.py
Labels: compiler

#2541 arch: add missing openmp flag for aomp compiler
  devito/arch/compiler.py
Labels: arch
