Repository devitocodes/devito, pull requests merged in 2025-03, with the labels that each got.

#2548 compiler: Fix update_properties
  devito/ir/support/properties.py
Labels: bug-py-minor

#2533 misc: Update advisor with oneAPI 2025
  benchmarks/user/advisor/README.md
  benchmarks/user/advisor/roofline.py
  benchmarks/user/advisor/run_advisor.py
  conftest.py
  devito/arch/archinfo.py
  devito/operator/operator.py
  devito/operator/profiling.py
  examples/performance/02_advisor_roofline.ipynb
  tests/test_benchmark.py
Labels: documentation

#2550 ci: Fix docker codecov
  .github/workflows/asv.yml
  .github/workflows/docker-devito.yml
  .github/workflows/examples-mpi.yml
  .github/workflows/examples.yml
  .github/workflows/flake8.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  .github/workflows/release-notes.yml
  .github/workflows/triggers.yml
  .github/workflows/tutorials.yml
  docker/entrypoint.sh
Labels: testing

#2552 misc: update all link to main
  .github/workflows/asv.yml
  .github/workflows/docker-devito.yml
  .github/workflows/examples-mpi.yml
  .github/workflows/examples.yml
  .github/workflows/flake8.yml
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  .github/workflows/release-notes.yml
  .github/workflows/triggers.yml
  .github/workflows/tutorials.yml
  CONTRIBUTING.md
  FAQ.md
  README.md
  benchmarks/user/README.md
  benchmarks/user/advisor/README.md
  binder/README.md
  devito/_version.py
  docker/Dockerfile.nvidia
  examples/README.md
  examples/cfd/09_Darcy_flow_equation.ipynb
  examples/compiler/00_index.ipynb
  examples/performance/00_overview.ipynb
  examples/seismic/acoustic/acoustic_time_update_nb.ipynb
  examples/seismic/self_adjoint/sa_01_iso_implementation1.ipynb
  examples/seismic/self_adjoint/sa_02_iso_implementation2.ipynb
  examples/seismic/self_adjoint/sa_03_iso_correctness.ipynb
  examples/seismic/tutorials/04_dask.ipynb
  examples/seismic/tutorials/04_dask_pickling.ipynb
  examples/seismic/tutorials/08_snapshotting.ipynb
  examples/userapi/05_conditional_dimension.ipynb
  setup.py
  versioneer.py
Labels: misc

#2556 install: Add packaging to requirements
  requirements.txt
Labels: dependencies

#2555 compiler: Enhance IR for GPU codegen
  devito/ir/support/basic.py
  devito/types/array.py
Labels: compiler

#2557 dsl: ensure SparseFunction coordinates and point symbols are always real
  devito/operations/interpolators.py
  devito/types/sparse.py
  tests/test_interpolation.py
  tests/test_sparse.py
Labels: API

#2558 compiler: Tweak init_core/halo properties
  devito/ir/support/properties.py
Labels: compiler

#2560 compiler: Fix reduction multi_partile
  devito/passes/clusters/blocking.py
  devito/symbolics/extended_dtypes.py
Labels: compiler

#2562 compiler: revert broken reduce par_tile
  devito/mpi/distributed.py
  devito/passes/clusters/blocking.py
Labels: bug-py
