Repository devitocodes/devito, pull requests merged in 2025-07, with the labels that each got.

#2652 compiler: add top description to generated file
  devito/ir/iet/visitors.py
  devito/operator/operator.py
  examples/cfd/01_convection.ipynb
  examples/cfd/01_convection_revisited.ipynb
  examples/compiler/01_data_regions.ipynb
  examples/compiler/03_iet-A.ipynb
  examples/mpi/overview.ipynb
  examples/performance/00_overview.ipynb
  examples/performance/01_gpu.ipynb
Labels: compiler

#2653 deps: Bump upper NumPy version to 2.3.1
  requirements.txt
Labels: dependencies

#2621 compiler: Lazy IET visitors + Search
  devito/ir/iet/visitors.py
  devito/symbolics/search.py
Labels: compiler

#2662 mpi: fix allreduce iteration space
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pytest-gpu.yml
  devito/ir/clusters/algorithms.py
  devito/ir/iet/nodes.py
  devito/ir/iet/visitors.py
  devito/passes/iet/misc.py
  pyproject.toml
  tests/test_mpi.py
Labels: MPI, compiler

#2664 compiler: fix temp/array alloc
  devito/arch/compiler.py
  devito/ir/cgen/printer.py
  devito/passes/iet/definitions.py
  devito/symbolics/extended_dtypes.py
  devito/symbolics/manipulation.py
  examples/mpi/overview.ipynb
  examples/performance/00_overview.ipynb
  tests/test_linearize.py
Labels: compiler

#2675 Revert "compiler: Cache `Scope` + `Dependence` instances"
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/analysis.py
  devito/ir/clusters/visitors.py
  devito/ir/support/basic.py
  devito/operator/operator.py
  devito/tools/memoization.py
  tests/test_ir.py
  tests/test_tools.py
Labels: bug-py

#2676 compiler: Fix HaloTouch hashing
  devito/mpi/halo_scheme.py
  tests/test_symbolics.py
Labels: bug-py

#2677 compiler: Reapply "Cache `Scope` + `Dependence` instances"
  devito/ir/clusters/algorithms.py
  devito/ir/clusters/analysis.py
  devito/ir/clusters/visitors.py
  devito/ir/support/basic.py
  devito/operator/operator.py
  devito/tools/memoization.py
  tests/test_ir.py
  tests/test_tools.py
Labels: compiler, performance

#2679 compiler: Call set_device in pthreads
  devito/passes/iet/asynchrony.py
  devito/passes/iet/langbase.py
Labels: bug-performance-gpu

#2685 data: prevent mpi comm with single rank
  devito/data/data.py
  examples/seismic/self_adjoint/sa_03_iso_correctness.ipynb
  examples/seismic/self_adjoint/test_wavesolver_iso.py
Labels: MPI

#2684 ci: Set CONTAINER_NAME within a step.
  .github/workflows/docker-devito.yml
  .github/workflows/pytest-gpu.yml
Labels: CI

#2688 misc: Switch mpi-x pub to ieee link
  CITATION.md
Labels: misc

#2689 compiler: Avoid generating parentheses when not needed
  devito/ir/cgen/printer.py
  devito/symbolics/queries.py
  examples/mpi/overview.ipynb
  examples/performance/00_overview.ipynb
  tests/test_iet.py
Labels: compiler

#2559 dsl: Expand derivative
  devito/finite_differences/derivative.py
  devito/finite_differences/differentiable.py
  devito/mpatches/__init__.py
  devito/mpatches/as_independent.py
  tests/test_derivatives.py
  tests/test_pickle.py
Labels: API
