Repository devitocodes/devito, pull requests merged in 2025-05, with the labels that each got.

#2594 deps: upper bound on codepy due to breaking latest
  requirements.txt
Labels: dependencies

#2596 deps: Add upper bound to all deps to avoid surprises
  requirements-nvidia.txt
  requirements-optional.txt
  requirements-testing.txt
  requirements.txt
Labels: dependencies

#2575 api: revamp subsampling factors to avoid duplicates
  devito/deprecations.py
  devito/ir/equations/equation.py
  devito/ir/support/guards.py
  devito/symbolics/extended_sympy.py
  devito/types/dimension.py
  devito/types/grid.py
  tests/test_dimension.py
  tests/test_pickle.py
Labels: bug-py, API

#2597 api: Add DEVITO_DEVICE_DEFAULT env var
  FAQ.md
  devito/arch/archinfo.py
  devito/parameters.py
  devito/types/dimension.py
Labels: API

#2601 compiler: Fixup factor overriding
  devito/types/dimension.py
  tests/test_dimension.py
Labels: bug-py

#2602 mpi: Fix halo exchanges from BundleViews
  devito/mpi/routines.py
Labels: MPI, bug-C

#2603 misc: Purge abc.abstractproperty as it is deprecated
  devito/ir/support/space.py
  devito/types/args.py
  devito/types/basic.py
Labels: misc

#2604 api: fix kwargs processing for tensor functions
  devito/builtins/initializers.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/tensor.py
  docker/Dockerfile.devito
  tests/test_tensors.py
Labels: API

#2605 deps: Update minimal for sympy and numpy
  .github/dependabot.yml
  .github/workflows/pytest-core-nompi.yml
  .github/workflows/pythonpublish.yml
  devito/__init__.py
  devito/_version.py
  devito/types/basic.py
  devito/types/caching.py
  devito/types/tensor.py
  pyproject.toml
  requirements.txt
  setup.py
  versioneer.py
Labels: dependencies

#2612 misc: remove unnecessary files with pyproject
  .github/workflows/flake8.yml
  devito/_version.py
  environment-dev.yml
  pyproject.toml
  requirements-optional.txt
  requirements-testing.txt
  requirements.txt
  setup.cfg
Labels: installation

#2598 compiler: Add VectorAccess as an internal type
  devito/arch/compiler.py
  devito/ir/cgen/printer.py
  devito/symbolics/extended_sympy.py
  tests/test_symbolics.py
Labels: compiler

#2613 install: switch to dynamic version to avoid _version file issue
  devito/__init__.py
  pyproject.toml
Labels: installation

#2614 arch: Improve GPU autodetection
  devito/arch/archinfo.py
Labels: arch

#2619 arch: Use the node's max memory transaction size
  devito/arch/archinfo.py
  tests/test_gpu_common.py
Labels: bug-C

#2620 arch: fix json erro with no card
  devito/arch/archinfo.py
Labels: arch
