Repository devitocodes/devito, pull requests merged in 2025-04, with the labels that each got.

#2566 compiler: Allow str cast type
  devito/operator/profiling.py
  devito/symbolics/extended_sympy.py
  devito/tools/dtypes_lowering.py
  examples/seismic/tutorials/13_LSRTM_acoustic.ipynb
  requirements.txt
  tests/test_symbolics.py
Labels: compiler

#2567 compiler: Fix reconstruction/pickling of low level objects
  devito/passes/clusters/unevaluate.py
  devito/passes/iet/definitions.py
  devito/symbolics/manipulation.py
  devito/types/array.py
  tests/test_pickle.py
  tests/test_symbolics.py
Labels: bug-C

#2565 examples: Fix norm for space order 4
  examples/seismic/tutorials/05_staggered_acoustic.ipynb
Labels: examples

#2568 deps: Add pillow version requirement
  requirements-optional.txt
Labels: dependencies

#2571 compiler: Fix uxreplace behaviour with numeric expressions
  devito/symbolics/manipulation.py
  tests/test_symbolics.py
Labels: bug-C-minor

#2572 CI: Ensure docker errors at test failure with codecov
  docker/entrypoint.sh
Labels: CI

#2539 tests: Remove floating point equality assertions
  tests/test_symbolics.py
Labels: testing

#2582 mpi: Fix correctness of halo exchanges for Bundles
  devito/mpi/halo_scheme.py
  devito/mpi/routines.py
  devito/tools/data_structures.py
  devito/tools/dtypes_lowering.py
Labels: MPI

#2584 Update 20.04 runners to 22.04
  .github/workflows/pytest-core-mpi.yml
  .github/workflows/pytest-core-nompi.yml
Labels: CI

#2578 compiler: Fix issue 2577 - edit printer for unevaluation Mul
  .github/workflows/pytest-core-nompi.yml
  devito/finite_differences/differentiable.py
  devito/symbolics/extended_sympy.py
  devito/tools/utils.py
  examples/seismic/tutorials/05_staggered_acoustic.ipynb
  tests/test_dse.py
  tests/test_symbolic_coefficients.py
  tests/test_symbolics.py
Labels: compiler

#2583 api: Fix staggering setup and tensor rebuilding
  devito/finite_differences/derivative.py
  devito/finite_differences/operators.py
  devito/finite_differences/rsfd.py
  devito/types/basic.py
  devito/types/dense.py
  devito/types/tensor.py
  devito/types/utils.py
  tests/test_staggered_utils.py
  tests/test_tensors.py
Labels: API

#2589 compiler: Avoid nvc++ array reductions and add MPI fallback
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/mpi.py
Labels: bug-C-minor

#2591 api: Add retrocompat to is_imaginary for older sympy
  devito/types/basic.py
  tests/test_symbolics.py
Labels: bug-py, dependencies

#2564 dsl: Add Real, Imag, and Conj operators
  .github/workflows/pytest-core-nompi.yml
  devito/core/__init__.py
  devito/core/cpu.py
  devito/core/gpu.py
  devito/finite_differences/differentiable.py
  devito/finite_differences/tools.py
  devito/ir/iet/visitors.py
  devito/operator/operator.py
  devito/passes/clusters/aliases.py
  devito/passes/clusters/cse.py
  devito/passes/iet/langbase.py
  devito/passes/iet/languages/C.py
  devito/passes/iet/languages/CXX.py
  devito/passes/iet/languages/openmp.py
  devito/passes/iet/languages/targets.py
  devito/tools/dtypes_lowering.py
  examples/performance/01_gpu.ipynb
  tests/test_builtins.py
  tests/test_cinterface.py
  tests/test_cse.py
  tests/test_dle.py
  tests/test_dse.py
  tests/test_dtypes.py
  tests/test_linearize.py
  tests/test_operator.py
  tests/test_skewing.py
  tests/test_symbolics.py
  tests/test_unexpansion.py
  tests/test_visitors.py
Labels: API

#2590 misc: Update FAQ.md
  FAQ.md
Labels: documentation
